### ISSUE TITLE
changelog not updated

### ISSUE THREAD

**Issue by inglesuniversal** [jackocnr/intl-tel-input#1068]
I was notified of an update by you just a few minutes ago.

Checking the changelog it shows been updated last year.

Are you going to include your latest updates on it soon?

Best regards and stay safe

**Comment by jackocnr** [comment]
Yeah sorry, I haven't had much time recently. The last version in the changelog is v16.0.0, and honestly since then it's pretty much just been re-building the libphonenumber script to be the latest version, and a few bug fixes. Best thing to do for now is just scroll through the commit history - there's not much!

Additionally, I would welcome a PR to update the changelog! Thanks. Closing for now.
