### ISSUE TITLE
Javascript not loading 

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [jackocnr/intl-tel-input#1078]
### Steps to reproduce
I followed the "Getting started"

### Expected behavior
It's supposed to show the dropdown with the flags etc

### Actual behavior
The javascript didn't load I believe since after inspecting my HTML and the demo HTML they weren't similar and on the UI the flags etc weren't showing.

My code:
`<link rel="stylesheet" href="{{ url_for('static', filename='css/intlTelInput.min.css') }}">`
The link tag is inisde the head tag

```
<input type="tel" id="phone">
<script src="{{ url_for('static', filename='js/intlTelInput-jquery.min.js') }}"></script>
    <script>
      var input = document.querySelector("#phone");
      window.intlTelInput(input, {
        // any initialisation options go here
      });
    </script>
```
I have this part of the code inside the body tags.

I'm using a flask to load the static files and all are giving 200 success responses.

**Comment by jackocnr** [comment]
Well one problem is that you're loading the jquery version of the plugin, and then using the pure JS initialisation code. I would switch to loading the pure JS version of the plugin.

But aside from that, if the issue is just how to load a script onto your page, then that's outside of the scope of support I can provide - I suggest you ask on StackOverflow. Best of luck.
