### ISSUE TITLE
A character string is returning a -99 (Broken) error code

### ISSUE THREAD

**Issue by Sako73** [jackocnr/intl-tel-input#1125]
https://github.com/jackocnr/intl-tel-input/blob/4172f50a8025399f6984f308f96c30cec6eb7ae1/src/js/utils.js#L84

I create the client-side input, set the value to "aaaaa" and I call ```isValidNumber()```, and I get back an error code of "-99", which says that it is broken.

Am I missing a configuration step, or is this an issue? Please let me know if you need more information. Thanks.

**Comment by jackocnr** [comment]
isValidNumber always returns a boolean. it's only if you call getValidationError that you might get -99. In this case, it's unable to provide a specific issue with the number, because there is no number at all. So if getValidationError does not return a known error code, then you need to show a generic error message instead.

**Comment by Sako73** [comment]
Thanks!
