### ISSUE TITLE
Country with area code show incorrect number.

### ISSUE THREAD

**Issue by NattawatPin** [jackocnr/intl-tel-input#1212]
### Steps to reproduce
1.  https://intl-tel-input.com/
2.  Click flag.
3.  American Samoa, Anguilla, Antigua and Berbuda etc.. show only +1 no area code.

**Comment by jackocnr** [comment]
In the flag dropdown, we only show the international dial code, not any local area code, as many countries have multiple area codes.

**Comment by paddotk** [comment]
@jackocnr As for various American countries, this is an issue as the area code is part of a dial code. For instance, the USA has +1 as dial code but American Samoa +1684. Yet both, as wel as other NPAP countries, are all displayed with +1 as the dial code in the dropdown.
![image](https://user-images.githubusercontent.com/11683974/151334004-afe954de-7766-4271-8c2f-5c4d6ae4ae11.png)

I think 'area' code is an ambiguous term here because it refers to whole countries in this case.

**Comment by weilingc** [comment]
> @jackocnr As for various American countries, this is an issue as the area code is part of a dial code. For instance, the USA has +1 as dial code but American Samoa +1684. Yet both, as wel as other NPAP countries, are all displayed with +1 as the dial code in the dropdown. ![image](https://user-images.githubusercontent.com/11683974/151334004-afe954de-7766-4271-8c2f-5c4d6ae4ae11.png)
> 
> I think 'area' code is an ambiguous term here because it refers to whole countries in this case.

I encountered this issue as well. Have they gotten it fixed?
