### ISSUE TITLE
Dom size is getting huge when multiple usage.

### ISSUE THREAD

**Issue by ilyasozkurt** [jackocnr/intl-tel-input#1292]
Hello,

When you use this plugin multiple in a page. Dom size goes huge because of initial country list. Is it possible to keep list in memory as a js variable, then use to render it when focused. 

Google says a page must be around 1500 doms.

Like: https://prnt.sc/24tijqz

This elements must not be here. 

Thank you.

**Comment by gurbuzyagiz** [comment]
Have You Found a Solution Yet?

**Comment by ilyasozkurt** [comment]
@gurbuzyagiz Actually, I solved my own problem with lazy load implementation using https://github.com/silvestreh/onScreen. This is not the absolute solution for this. These options must ve moved to memory.

**Comment by jackocnr** [comment]
Apologies for the delay in getting to this, life sometimes gets in the way!

But as I think about this, I'm afraid it might not be as simple as just storing the dropdown in memory instead of in the DOM, as the problem is then when the user clicks the selected flag, we have to inject all of those DOM nodes, which looks like 244 list items, with 5 nodes each = 1220 nodes. That might cause some lag in the page, especially on slower devices, which would be a bad UX.

I think the proper solution here is to use one of those scrolling libraries, so we only inject the list items that are currently visible as the user scrolls through the list. But that is a much bigger job.

Out of interest, how many instances of the plugin are you using on your page, and are you actually seeing perf issues?

I wonder if, for now, the solution is as you say: to handle this issue outside of the plugin, with a library like the one you linked to, so that you're only rendering the plugin on the page when it is visible.

**Comment by jackocnr** [comment]
Haha, with that said, I've just remembered that `dropdownContainer` option does exactly what you want - so you can just use that!
