### ISSUE TITLE
Country Select to search by numbers

### ISSUE THREAD

**Issue by erictehyc** [jackocnr/intl-tel-input#1368]
Hello, I think this feature would be useful, in addition to search by country name

### Steps to reproduce
1.  Select the country code dropdown
2.  Type numbers

### Expected behaviour
It should show countries that match the typed numbers

### Actual behaviour
Nothing happens

**Comment by mbardelmeijer** [comment]
We would be interested in this as well. 👍

**Comment by jackocnr** [comment]
Apologies for the delay in getting to this. Sometimes life gets in the way!

This is an interesting idea, but I don't think it would work very well. The reason this works with country names is because they're in alphabetical order, so you type "ch" and you see Chad, Chile, China next to each other and it's easy to select the right one quickly. But if you type "1" what should you see? There are lots of countries with that dial code, and they're spread out through the whole dropdown, so I don't think it would make sense to pick any one of them over the others, which the user might be hoping to get to. Closing for now.

**Comment by jackocnr** [comment]
You can now search for dial codes using the new option `countrySearch` in v18.5.1. Let me know what you think!
