### ISSUE TITLE
[Query] Integrating with react

### ISSUE THREAD

**Issue by cdwijayarathna** [jackocnr/intl-tel-input#1402]
Is it possible to use this module in a react project? If yes, is there any documentation that I can follow?

I am aware of the react-intl-tel-input module, but it seems to be no longer maintained and also does not support react 16+ versions.

**Comment by jackocnr** [comment]
I have used it in a React project previously without much bother. Just make sure the parent component doesn't re-render all the time!

Are you having any problems in particular?

**Comment by jackocnr** [comment]
I just threw this codepen together, using the plugin within a react (v18) functional component, in case that's useful: https://codepen.io/jackocnr/pen/RwePbZg

I'll close this for now, but do let me know if you have any specific problems.

**Comment by officert** [comment]
@jackocnr I noticed in the CodePen auto formatting doesn't seem to work. I noticed this in my own project, with React, so I was looking at your example. But the issue seems to happen there as well.

<img width="313" alt="Screen Shot 2023-09-07 at 11 41 37 PM" src="https://github.com/jackocnr/intl-tel-input/assets/4620560/ca188536-cac6-4686-bd26-670e90b109d4">

**Comment by officert** [comment]
ignore my previous message, looks like auto format on type is no longer supported.
I was able to get it working by calling `setNumber(getNumber())` on change events. Here's an updated CodePen for anyone using React and running into this:

https://codepen.io/tofficer/pen/xxmgJVR
