### ISSUE TITLE
Morocco number can start with 7 or 5 like +212772772277 OR +212567787788 

### ISSUE THREAD

**Issue by hajiblargo** [jackocnr/intl-tel-input#1406]
### Steps to reproduce
1.  SELECT Morocco +212
2.  Type this number 752556677
3.  Not accepted and just number start with 6 accepted

### Expected behaviour
Morocco numbers can start with 7 and 5 also

### Actual behaviour
Tell us what actually happens

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jackocnr** [comment]
I've just released a new version, which uses the latest version of libphonenumber, so give that a try first, otherwise:

We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

**Comment by hajiblargo** [comment]
Yes i've just try in the libphonenumber with this number +212752288895 but is invalid
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76794023/224307464-61eeaff4-50dd-470b-9a72-9a55bd4a55b0.png">

**Comment by jackocnr** [comment]
Sounds like it's an issue for libphonenumber then. I'll close this for now.

**Comment by mimoudix** [comment]
same issue brother.
