### ISSUE TITLE
isValidNumber returns true for numbers not insides only country array

### ISSUE THREAD

**Issue by ibrahimBanat** [jackocnr/intl-tel-input#1458]
### Steps to reproduce
1.  add only the country item to be only 'UK'
2.  grab a number from another country that starts with + and paste it into the input 

### Expected behaviour
the input should recognize the pasted number and the isValidNumber should return false

### Actual behaviour
grab a number from another country that starts with + and paste it into the input the flag will be unknown and isValidNumber will return true.

**Comment by jackocnr** [comment]
Hmm I see where you're coming from, but I think it would be confusing if the validator returned false for a valid number, just because the country isn't shown in the list.

I would say just do this yourself - just check if there is a valid country selected or not - one way to do this would be to use `getSelectedCountryData`.
