### ISSUE TITLE
preferredCountries not working

### ISSUE THREAD

**Issue by pedro-dalben** [jackocnr/intl-tel-input#1504]
even adding preferredCountries, it does not apply in the dropdown.
`const intlTelInputInstance = intlTelInput(input, {
      utilsScript: 'intl-tel-input/build/js/utils.js',
      hiddenInput: function () {
        return (input || {}).dataset.hiddenInputData
      },
      initialCountry: 'us',
      preferredCountries: ['us', 'br'],
      autoPlaceholder: 'aggressive',
      autoInsertDialCode: true,
    })`
    
![image](https://github.com/jackocnr/intl-tel-input/assets/57180027/ab272e1f-779c-489f-9670-8a68d15ca11e)
version 19.2.1

**Comment by jackocnr** [comment]
The new country search feature is incompatible with preferred countries. So you'll have to disable `countrySearch` if you want to use `preferredCountries`.

**Comment by cameron-emburse** [comment]
What was the reasoning for this? I don't see why you can't have the list ordered however you want and still allow searching

**Comment by jackocnr** [comment]
Well the preferredCountries option creates two groups of countries within the country list, separated by a grey divider, and I thought it would be confusing to display two different ways of organising the countries simultaneously: both (1) search (which is actually just doing a filter of the already displayed countries), and at the same time, (2) to show the countries grouped by some other criteria (AKA the preferredCountries option). As a user, I would not know what to expect when I started typing a search query - what would happen to the groups? Would I see results from both groups separately? So I think it would be confusing.

One alternative to this would be: instead of having two groups of countries separated by a grey divider, is, like you say, to just allow you to order the countries however you want. Then you can put the countries that you think are most likely to be selected near the top, which is similar to google search predictions. But it is not the same as that because, as I say, it's not really doing a search, it's actually doing a filter of the already displayed list of over 200 countries. But when you first open the dropdown you can only see aprx 5 countries, and if some of those are preferredCountries, custom selected and with no clear ordering, then you might assume those are the only options... it might not be clear that you can actually type any country name you like... whereas if they're alphabetically ordered, it's clear that you're just looking at the first 5 in a long list. 

Additionally, I would argue that having the search input, (which is automatically focused), is so fast and easy to use, that it doesn't really help all that much to put certain countries right at the top of the list - if all the user has to do is type 2-3 characters and press enter... we're talking about saving some users (who want to select a preferred country) a second or two, while other users (who want to select a non-preferred country) might have a confusing experience.

So I'm in two minds about it. Does anyone else have any thoughts? cc: @anthony0030

**Comment by anthony0030** [comment]
I can visualize what you are saying about the preferred countries, it would cause confusion in the user journey.

Preferred countries feel like a legacy feature that has been grandfathered in.
When the search feature came out preferred countries went out the window.

After reviewing the input on the demo site without modifications, I noticed that ```Åland Islands``` is at the bottom of the list as it has a strange circle on the A, This seems to be the correct way of spelling it.

My proposal for the ordering is to first order by dialing the code and then by country name in the currently selected language. This would prevent all confusion of ordering such as ```Åland Islands```.  

Countries have an endonym, an official name and exonyms, so for example; Someone scrolling to find Germany are they looking for ```Germany``` , ```Deutschland``` , ```Γερμανία```,  or ```Federal Republic of Germany```? As the input is in English for all the countries the answer would be that it is in the English exonyms ```Germany```.



Because the dialing codes are always in a decimal positional numeral system (Base-10) this would be in my opinion better as it is universal in all languages.


Disclosure: I am not currently officially a maintainer of this project. All the Opinions in this post are my own and my not reflect the opinions of @jackocnr.

**Comment by jackocnr** [comment]
> I can visualize what you are saying about the preferred countries, it would cause confusion in the user journey.

I agree 👍 

> My proposal for the ordering is to first order by dialing the code and then by country name

So if we order first by dial code, that would be +1 first (so all the NANP countries: American Samoa, Anguilla, Antigua, Bahamas, Barbados etc, all the way to United States at the end), then +7 (Kazakhstan, Russia), then +20 (Egypt), +27 (South Africa), etc...

So the country list would be in this order:

- American Samoa +1
- ........
- United States +1
- Kazakhstan +7
- Russia +7
- Egypt +20
- South Africa +27
- Greece +30
- ........

I agree that this would solve some confusion around countries/territories with the same dial code, but as you can see, you totally lose the alphabetic ordering, which for me makes it way less predictable and actually adds a bunch of confusion, as I think most people are only really familiar with a handful of dial codes (or possibly even just their own), and so using dial codes as the primary ordering wouldn't be the most helpful/intuitive for most people, in my opinion.

With that said, I think with the next major release, I will remove the countrySearch option (leaving it enabled for everyone), and as such, I will remove the preferredCountries functionality altogether, and I'm considering adding a new option (e.g. countryOrder) to allow devs to order countries however they want, which would solve the problem of people wanting to put the most common ("preferred") countries at the top of the list, and it would also allow you to order the countries by dial code first if that's what you want to do (you could grab all the country data with `getCountryData` and do some pre-processing to generate this list how you want it). What do you think?

**Comment by anthony0030** [comment]
>  I will remove the countrySearch option (leaving it enabled for everyone)

It's such a key piece of functionality, I can see that it would be useful to always have it, If someone wants it gone CSS.

>  I will remove the preferredCountries functionality altogether

One the search functionality came out it became somewhat obsolete, The cool thing about the search is that it also matches the dialing code.

> I'm considering adding a new option (e.g. countryOrder).

Would this take a function or an array of strings of the iso-codes?
IF it took a function that gets passed the result from getCountryData and would be required to return the array, this way you could remove the excluded countries as well as the user could remove them in the function.

**Comment by jackocnr** [comment]
> IF it took a function that gets passed the result from getCountryData and would be required to return the array, this way you could remove the excluded countries as well as the user could remove them in the function.

Hmm it's an interesting idea. I suppose we could then get rid of excludeCountries and onlyCountries. It would just add a little bit of complexity for the developer as they would have to write a little bit of logic e.g. a filtering function (in the case of excludeCountries). The other downside is: I was actually thinking countryOrder could be forgiving and allow you to not bother specifying every single country - so if you just specify 1 or 2, e.g. ["us", "gb"] then those would appear first, followed by the rest (which would assume the default alphabetical ordering). I think I prefer keeping it simple for now and separating the concerns of the options - so excludeCountries is for which countries show, and countryOrder is for how they are ordered.

**Comment by OzanKurt** [comment]
This used to work on v14, why did you remove an amazing feature?

**Comment by jackocnr** [comment]
@OzanKurt did you read the discussion in this thread? See countryOrder option which allows you to do something very similar.

**Comment by TomsProject** [comment]
> The new country search feature is incompatible with preferred countries. So you'll have to disable `countrySearch` if you want to use `preferredCountries`.

Is this option totally removed now? Have tried disabling `countrySearch`, however, it is still not working.

Also I think `preferredCountries` is to allow users to choose their countries with a few clicks. I guess a way to maintain both of these options is: 
1) If users haven't typed in the search field, keep the two fields separated. 
2) After users typed in the search field, directly show the searching results and ignore the two parts (organize all countries altogether).

**Comment by Pavel-Pavek** [comment]
It's really annoying that new versions, instead of adding new features, drop important ones :-(

Dropping preferredCountries was a big mistake.
After hours and hours of searching and testing, I'm sticking with version 17 :-(((

The developers could at least comment on why 
preferredCountries was removed, and if they see that users are unhappy with it, why don't they put it back again?

**Comment by jackocnr** [comment]
If people are still looking for this `preferredCountries` functionality, it's actually super easy to reproduce it:

Previously:

```js
preferredCountries: ["us", "gb"]
```

Now:

```js
countryOrder: ["us", "gb"]
```

And simply add the divider yourself with a single CSS rule (replace "gb" in the selector with your last country code):

```css
.iti__dropdown-content:has(.iti__search-input:placeholder-shown) .iti__country[data-iso2="gb"] {
  border-bottom: 1px solid var(--iti-border-color);
}
```

This CSS selector cleverly only adds the border when the country search is empty, as it doesn't make sense to show the divider after you've filtered the countries.

NOTE: if you have countrySearch disabled (not recommended), you would need a slightly different selector (again, replace "gb" in the selector with your last country code):

```css
.iti__country[data-iso2="gb"] {
  border-bottom: 1px solid var(--iti-border-color);
}
```
