### ISSUE TITLE
Disable alphabetic chars (etc)

### ISSUE THREAD

**Issue by mikadev** [jackocnr/intl-tel-input#1508]
It would be nice to add an option to allow only number and some spécial characters like + ()...

**Comment by jackocnr** [comment]
Can you describe your use case, and why you think this would improve the user experience?

**Comment by mikadev** [comment]
Exactly like this one for example ==> https://louismazel.github.io/vue-phone-number-input/ you can't entering **a,b,c** or other irrelevant character for phone number

**Comment by jackocnr** [comment]
I understand what you mean, I'm just not convinced that it is a better UX.

Basically, you're saying: if the user types an irrelevant character, then it's better to ignore it. It raises the questions (1) why would the user type one of those chars in the first place? and (2) if they do try to type one of those characters, why is it better to silently block it, than to let them do whatever they want?

In my opinion, it's never a good idea to silently block a user's actions - I think it can feel like something is broken.

**Comment by mikadev** [comment]
I point of vue but for me is exactly like a number input is expected number only the same here. In my point entering non wanted character make me feel that something is broken

**Comment by jackocnr** [comment]
Thanks for sharing your experience (that if you accidentally type an irrelevant char into an input, and it lets you do that, then it feels broken).

For me, my experience is that I expect to be able to type whatever I want, and if that silently fails then it feels broken.

You've linked a couple of examples of other plugins that do block irrelevant chars, but the phone inputs on the majority of the major websites I've checked do not do this (e.g. Google Contacts, iCloud Contacts etc).

I'm not going to add this functionality now, but I am open to adding it in the future IF I hear from lots of people that this is something they really want.

For now, this should be easy to add yourself, e.g.

```js
document.getElementById("phone").addEventListener("keydown", (e) => {
    if (e.key && e.key.length === 1 && /[^0-9+\-.() ]/.test(e.key)) e.preventDefault();
});
```

**Comment by mikadev** [comment]
So why in the mobile phone the plugin display only number is exactly like you do a phone call you don't expect to enter ABC, btw maybe it can be an option ?

**Comment by jackocnr** [comment]
> why in the mobile phone the plugin display only number

I assume you're talking about mobile browsing, where tapping on inputs with type=tel opens the numeric keypad. This is because that's all you should need to type in that input. Same with a phone dialer. But we're not talking about those situations. We're talking about a situation where the user has a full keyboard in front of them and might for some reason type something else.

For posterity, I can think of 3 situations in which someone might type an irrelevant character (let me know if you can think of any more!):
1. They accidentally hit the wrong key on the keyboard - in this case, it's probably just helpful if it is silently ignored
2. They're confused and think the input is for something else - in this case, it will just feel broken, though it MIGHT make them look again and realise what the input is actually for. Then again, it might not.
3. They try to paste their phone number into the input, but for whatever reason, something else was in their clipboard (this often happens to me!) - in this case, silently failing will just feel broken and will be confusing and annoying

As I said before, I will consider adding this feature in the future (yes as an option), but only if enough people would find it useful 👍

**Comment by mikadev** [comment]
Great thanks i will try this :)
