### ISSUE TITLE
Issue for the phone valid in react component

### ISSUE THREAD

**Issue by chayutWQ** [jackocnr/intl-tel-input#1546]
### Steps to reproduce
1.  try to fill input phone +669223800022 on react component return valid
2.  but I try to fill input +669223800022  on example this https://intl-tel-input.com/examples/validation.html  return in-valid

import IntlTelInput from "intl-tel-input/react/build/IntlTelInput.esm";
import "intl-tel-input/build/css/intlTelInput.css";

<>
<IntlTelInput
                  initialValue={phone}
                  onChangeNumber={setValue}
                  onChangeValidity={setIsValid}
                  onChangeErrorCode={setErrorCode}
                  required
                  // any initialisation options from the readme will work here
                  initOptions={{
                    initialCountry: "auto",
                    utilsScript: "/intl-tel-input/js/utils.js?1709392860975"
                  }}
                />
{notice && <div className="notice">{notice}</div>}
</>

**Comment by jackocnr** [comment]
That's because the react component currently uses the default ("practical") validation method, whereas the demo page you linked to uses the more comprehensive "precise" validation method - you can read about the difference in the readme, or on the demo site. If you check the default (practical) validation demo page, you will see the number is marked as valid: https://intl-tel-input.com/examples/validation-practical.html

This raises a good point though - some people may want to use the precise validation method with the react component. I propose we add a "usePreciseValidation" (bool) prop to support this, which controls which validation method we use. I would welcome a PR to add this.

**Comment by jackocnr** [comment]
Added in v20.0.0
