### ISSUE TITLE
Advise: Multiple instances of intl-tel-input getting loaded, causing global "window" collision

### ISSUE THREAD

**Issue by postama** [jackocnr/intl-tel-input#1577]
Thank you for your excellent work on this library and on its maintenance. This is not a bug, nor a feature enhancement, but looking for advisement.

We have a page on our site that uses intl-tel-input. Recently, a 3rd party widget was added (https://www.leadconnectorhq.com/) which also uses intl-tel-input.

The problem is, that both scripts get loaded, and therefore both load `window.intlTelInputGlobal`. This conflict is causing one of the two to always break, since each version has one instance.

What options do we have at an implementation level? Are there ways we can avoid this clash?

I can see two possible solutions at a library level, which would both require changes (so non-ideal):
1. Modify library initialization to check for `window.intlTelInputGlobal`, and if it already exists, don't re-initialize. This seems like it could cause versioning problems if there are multiple different versions getting loaded though.
2. Allow for users to name their own instance instead of using the global "window". This is similar to how jQuery supports namespaces: https://stackoverflow.com/questions/1535691/how-to-change-namespace-of-jquery

**Comment by jackocnr** [comment]
> We have a page on our site that uses intl-tel-input. Recently, a 3rd party widget was added (https://www.leadconnectorhq.com/) which also uses intl-tel-input.

Wow, I guess this plugin is a victim of its own success! 🎉 

It's an interesting problem. I like the idea of borrowing from jQuery's `noConflict` mode.  The easiest way to handle this would be with a new initialisation option e.g. called `noConflict`, which takes a string e.g. "Postama", and uses that to modify the name of the global so it doesn't clash with any other e.g. changing `intlTelInputGlobals` to `intlTelInputGlobalsPostama`. The problem is that currently, `window.intlTelInputGlobals` gets defined as soon as the plugin script is parsed by the browser (before plugin initialisation), but thinking about it, we might be able to change that, so it doesn't get defined until the first initialisation - I need to look into this.

Additionally, we have the global `intlTelInputUtils` from when you load the utils script. In this case, it might be possible to do something similar, and in the `onload` handler that fires when the utils script has loaded, we immediately rename the global e.g. from `intlTelInputUtils` to `intlTelInputUtilsPostama`. 

Then we'll need to update all of the references to these globals in the code - possibly with something like the following:

```js
getGlobalsName() => `intlTelInputGlobals${this.options.noConflict}`;
getUtilsName() => `intlTelInputUtils${this.options.noConflict}`;

// existing code using these globals
const formatted = window[getUtilsName()].formatNumber(...);
// and
window.[getGlobalsName()].loadUtils(...);
```

**Comment by jackocnr** [comment]
Unfortunately, since we currently offer the [static method](https://github.com/jackocnr/intl-tel-input?tab=readme-ov-file#static-methods) `window.intlTelInputGlobals.getCountryData()` before the plugin is initialised, we will need to change how this works, and so it will be a breaking change, and so will have to wait until the next major release, which may not be for a while.

**Comment by postama** [comment]
Ahh okay, thank you for letting me know that, and for your detailed response.

**Comment by jackocnr** [comment]
I've just released v21.2.5 which includes a little fix, so from now on, it should still work fine if there are two plugin scripts on the page at the same time, as long as they're both using the same version of the plugin (starting with this new version). So if you can upgrade to this version in your own code, and get leadconnectorhq to do the same, then things should work ok. Then at least you have a way of making things work for now, until we're able to do the full `noConflict` implementation.

**Comment by jackocnr** [comment]
In v22.0.0 I've removed all of the globals vars, so if you upgrade to that version, it should no longer clash with any older version on the same page. Let me know if you have any issues.

**Comment by unicornsoftwareinc** [comment]
Hi @jackocnr , I'm also running into pretty much exactly this same issue with LeadConnecterHQ (AKA HighLevel). Looks like LeadConnecterHQ is running version 17.x and I've tested the latest version of this library and it runs into issues where HighLevel's ITI library overwrites mine. So when I attempt to get my phone number from my app's form, it fails.

I'm trying to understand your last couple comments, will this conflict / issue be resolved if we get HighLevel to update their version of this library to the latest?

Thanks in advance!
