### ISSUE TITLE
can you exclude the "Unknown" country from the input?

### ISSUE THREAD

**Issue by victorcalarasu** [jackocnr/intl-tel-input#1578]
### Steps to reproduce
1.  type +00 in the input 

### Expected behaviour
Could it be somehow added to the excludeCountries ?

### Actual behaviour
The flag changes to the Unknown flag

### Initialisation options
nothing in particular

**Comment by jackocnr** [comment]
So what do you want to happen when the user types "+00"?

**Comment by victorcalarasu** [comment]
was just wondering if it could be excluded in any way so that the user can't access it

**Comment by jackocnr** [comment]
Ok, say we exclude the globe image... then what would you want to happen when the user types "+00"?

Or perhaps you're saying you want to prevent the user from typing "+00"? If so, then how would you expect that to work?

**Comment by anthony0030** [comment]
How about making the color of the globe red when any invalid country code is input?


PS: Also have SR-only text?

**Comment by jackocnr** [comment]
One thing Stripe do with their phone input, is if you type + in the main phone input, it automatically opens the country dropdown and puts the + in the country search input instead, forcing you to select a country instead of type the dial code in the phone input, which I think would be a good solution to this problem.

**Comment by jackocnr** [comment]
Please try the new `separateDialCode` option in v22.0.0 which implements the above idea.

**Comment by anthony0030** [comment]
Seems to be working nicely.
