### ISSUE TITLE
Validation doesn't work for some phone numbers from Germany

### ISSUE THREAD

**Issue by impratick** [jackocnr/intl-tel-input#1615]
### Plugin version
v23.0.4

### Steps to reproduce
1. Select `Germany(+49)` as country code
2. Enter `0963199721` or `+49963199721` as the phone number

### Expected behavior
It should be identified as a valid phone number.

### Actual behavior
Being identified as an invalid phone number, however, it is valid.
Tested on [validation-practical demo](https://intl-tel-input.com/examples/validation-practical.html)

![image](https://github.com/jackocnr/intl-tel-input/assets/6824926/b6d695f4-4c1e-4d3e-aa04-510394bce99c)

**Comment by jackocnr** [comment]
The problem is that the number is a FIXED_LINE number and `isValidNumber` respects the `validationNumberType` option, which is MOBILE by default. If you need to accept other number types, you can change this option to `null`. Or alternatively, use `isValidNumberPrecise` (demo [here](https://intl-tel-input.com/examples/validation.html)), which I checked and it passes for this number.

**Comment by impratick** [comment]
Yes, I think this will help me. Thanks @jackocnr.
