### ISSUE TITLE
search field if one country?

### ISSUE THREAD

**Issue by Morbids** [jackocnr/intl-tel-input#1632]
If you set only one country in onlyCountries, then why display the search field?

**Comment by jackocnr** [comment]
If you're only allowing a single country, then why even let them open the dropdown? I would set `allowDropdown` to false in this case.

**Comment by Morbids** [comment]
I have these settings

"allowDropdown":false,
"autoPlaceholder":"off",
"dropdownContainer":null,
"formatOnDisplay":false,
"geoIpLookup":"ipapi",
"initialCountry":"ua",
"nationalMode":false,
"onlyCountries":["ua"],
"countryOrder":[],
"separateDialCode":true,
"useFullscreenPopup":false,
"strictMode":true,
"utilsScript":"utils.js"

**Comment by jackocnr** [comment]
Ok. And so does that solve your problem?

**Comment by Morbids** [comment]
No
Here's a video [](https://watch.wave.video/kBRwJuGj7mFL1M2h)

**Comment by jackocnr** [comment]
`separateDialCode` requires the dropdown, so it forces `allowDropdown` to be `true`. If you want to have `allowDropdown: false`, you'll need to set `separateDialCode: false`.

**Comment by jackocnr** [comment]
Yes, that is how allowDropdown=false works.

From the readme:

> if showFlags is enabled we display the selected flag on the right instead because it is just a marker of state

**Comment by jackocnr** [comment]
> otherwise it will be deleted

Are you concerned that the user will type their international dial code, and then delete it? Why would they do that?

Please can you describe the precise situation you're concerned about, breaking it down into simple steps, from when the plugin is first initialised, and the input is empty.

**Comment by jackocnr** [comment]
> if he does not enter the country code (no matter what country), it will not be possible to send an SMS message to the user

This is actually incorrect. It's enough for the user to enter their number in national format (without the international dial code), and then if you use `getNumber`, it will give you the full international number (including the international dial code). This is actually how the plugin is designed to work, which is why we show a national number placeholder by default, to encourage the user to do just this. Note that `getNumber` requires the utils script to be loaded - see [readme on how to load this](https://github.com/jackocnr/intl-tel-input/blob/master/README.md#loading-the-utilities-script).

> The question is completely different - is a search field necessary if there is 1 country, or 2 countries, or 3 countries, etc.,

Sure. Thanks for raising the question. For me, this is not something that should be decided by the plugin - it should be up to the dev to decide how they want this to work depending on their situation (e.g. it might depend on how many countries you can see at once in the dropdown etc, depending on their custom CSS), so this would require a new option to control it, and in my opinion, this is such an edge case that it's not worth implementing this right now. Especially in your case, where there is only 1 country, it doesn't make any sense to have a dropdown at all.

**Comment by jackocnr** [comment]
Upon further consideration, if you only want to show say 2-10 countries, then it makes sense to allow the dropdown, but remove the search feature. So I propose we re-add the `countrySearch` option, which decides if we show the search box or not (as well as the auto-focus functionality), and defaults to true. It should also be forced to true when separateDialCode is true, as that depends on the search feature. I don't have time to implement this myself right now, but I would be open to a pull request.

**Comment by jackocnr** [comment]
I've re-added the countrySearch option in v23.4.0
