### ISSUE TITLE
Country search box not working when initialized with "dropdownContainer" set to document.body in a Bootstrap modal

### ISSUE THREAD

**Issue by DamienLaw** [jackocnr/intl-tel-input#1704]
![image](https://github.com/user-attachments/assets/00f6173c-3503-4e26-a955-53b46bac0e90)

### Plugin version
v23.3.2 (latest)

### Steps to reproduce
1.  Place an input text inside a Bootstrap modal (Bootstrap v5.3.3 or v4.6.2)
2.  Initialize that input with `dropdownContainer` set to `document.body`.
3. Run the code and click on the flag button to bring up the dropdown.
4. Click on the "search" textbox on the dropdown and try to type something.
5. Example: https://codepen.io/damienlaw-the-scripter/pen/WNqQrrY

### Expected behaviour
Should be able to type something in the search textbox

### Actual behaviour
Search textbox is not receiving focus when clicking on it therefore unable to type anything at all in the textbox

### Initialisation options
`dropdownContainer` set to `document.body`

**Comment by jackocnr** [comment]
I initially thought it must be a CSS issue, e.g. with the z-index or some positioning issue or something, but I've done some investigating and concluded it must be an issue with the Bootstrap JS. If you exclude the Bootstrap JS and tweak the CSS to show the model, then it works fine. So I think the Bootstrap JS is swallowing the click/focus event somehow.

Anyway, I found a workaround: instead of setting `dropdownContainer` to `document.body`, you should set it to the modal element instead - in your example that would be `document.querySelector("#exampleModal")`.

**Comment by DamienLaw** [comment]
Weird, why is Bootstrap JS swallowing events of this particular search box but not others. This has led me to look into the event listener of the search box in DevTools.
![image](https://github.com/user-attachments/assets/bfd7211a-5800-4284-80bd-f52f17c9601f)

True enough, if I click on the underlined "Remove" button of the `focusin` event listener, the expected behaviour is restored. I didn't pursue further on my investigation though since your workaround works. Thanks.
