### ISSUE TITLE
Australian toll free number is invalid in practical validation

### ISSUE THREAD

**Issue by rajeshcheeti** [jackocnr/intl-tel-input#1738]
I am seeing a validation error with practical validation for toll free number for the country AU where as it is valid format in precise validation. But since precise validation updates regularly we would not want to switch to it. Example toll free number is **1800123456** I am able to reproduce this in https://intl-tel-input.com/examples/validation-practical.html

I verified this in [libphonenumber](https://github.com/googlei18n/libphonenumber) and this toll free number is giving the result as valid number.

### Plugin version
v23.8.0

### Steps to reproduce
1.  Go to https://intl-tel-input.com/examples/validation-practical.html
2.  Enter **1800123456** and click on validate
3.  Validation error displays

### Expected behaviour
Should accept the toll free number and return valid as validation response when selecting country as Australia and entering 1800123456

### Actual behaviour
It is giving validation error when toll free number (1800123456) entered

### Initialisation options
Able to reproduce this with any basic selections

**Comment by jackocnr** [comment]
> I am seeing a validation error with practical validation for toll free number for the country AU

This is because `validationNumberType` defaults to "MOBILE", which means `isValidNumber` only returns true for MOBILE numbers. If you change `validationNumberType` to `null`, then `isValidNumber` will return true for all types of number.

I realise we should mention this on the practical validation demo page - I will add this to my list!

**Comment by rajeshcheeti** [comment]
@jackocnr Thank you for the response. One question for you - I am currently using onChangeValidity() to control the validation error but if I change `validationNumberType` to `null`, then onChangeValidity() validation not working as expected. For example onChangeValidity() is returning true for  the number `1800123` for AU. But it is showing as invalid in https://intl-tel-input.com/examples/validation-practical.html. I thought onChangeValidity() use isValidNumber() output but looks like it is not. Is there any work around to fix this?

**Comment by jackocnr** [comment]
> if I change validationNumberType to null, then onChangeValidity() validation not working as expected. For example onChangeValidity() is returning true for the number 1800123 for AU. But it is showing as invalid in https://intl-tel-input.com/examples/validation-practical.html.

With validationNumberType=null, the validation will return true for that number, yes. The reason it doesn't on that demo page is because in that case it has the default value of validationNumberType, which is set to mobile only.

You can play with the options in this codepen: https://codepen.io/jackocnr/pen/NWZvVjZ?editors=0010
