### ISSUE TITLE
Russian phone numbers placeholder is incorrect

### ISSUE THREAD

**Issue by creative-guy** [jackocnr/intl-tel-input#1818]
It shows "8 (912) 345-67-89" - 11 digits. It should be just "(912) 345-67-89" - 10 digits. Mask is correct, it capped length to 10 digits, as it should. Just wrong placeholder.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please [file an issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md) with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by creative-guy** [comment]
Libphonumber seems okay, just checked it's output. Probably you are just using it not correct, or it is not really fit for your usage.
As I see, you took placeholder(mask) from "National format" field. And that is wrong usage. For same countries it's works fine, like example:

US: +1 (201) 555-0123
National format: (201) 555-0123

AL: +355 067 212 3456
National format: 067 212 3456

But some countries use country code equialent in national number, like:
RU: +7 (912) 345-67-89
National format: 8 (912) 345-67-89

BY: +375 029 191-19-11
National format: 8 029 191-19-11

Number "8" as a first digit - is not a part of a phone number, its a country code equivalent. So as a national format its right, but for mask(placeholder) - it is not right. Cause if we already have "+7" or "+375" - than we don't need this "8", as I said, "8" - is replacement for "+7" or "+375" in national format.

**Comment by jackocnr** [comment]
> Cause if we already have "+7" or "+375" - than we don't need this "8"

What do you mean when you say you already have "+7"?

I initially thought you meant you have separateDialCode enabled, which would display the +7 next to the typed number, but that can't be true because then the placeholder doesn't include the "8". So I don't understand what you mean when you say you already have the "+7".

By the way, if you set separateDialCode=true, (or even just nationalMode=false), there will be no "8" at the beginning of the placeholder. Have you tried using either of these options?

But I do agree there is currently a bug, as if you leave the initialisation options to the defaults (nationalMode=true and separateDialCode=false), and just set strictMode=true, then select Russia, you get a placeholder number (11 digits) which you can't actually type, as strictMode only allows 10 digits in this case, as you say. But from my current understanding, I think this is a problem with strictMode - that it should allow all 11 digits (when nationalMode is enabled). But I'm open to understanding it differently if you disagree.

e.g. in the UK, you have:

International format: +44 7400 123456
National format: 07400 123456

Notice we add a 0 at the beginning of the number in national format. In this case, we want the placeholder to display the extra 0 because nationalMode is enabled by default, which enables users to enter their number in the most familiar way - the way they are most used to typing it, seeing as how the +44 is not displayed anywhere. If you enable separateDialCode, and we display the +44 then it doesn't make any sense to add the 0. I assumed it was the same situation in Russia with adding the 8 in national format?

**Comment by creative-guy** [comment]
Yeah, I don't tried to play with "nationalMode" or "separateDialCode" parameters. Will try it later.

**Comment by jackocnr** [comment]
I've now fixed the bug where strictMode prevented you from typing the Russian placeholder number (in national format). That fix is included in v24.5.2.

And either of those 2 options mentioned should resolve your concern, so I'll close this issue for now, but do let me know if you're still having problems.
