### ISSUE TITLE
No country data

### ISSUE THREAD

**Issue by minhluan259** [jackocnr/intl-tel-input#1876]
### Plugin version
e.g. v24.7.0 (please try latest version)

### Expected behaviour
Many countries/sub-countries are not support in the list, so we need an option to allow display Global Flag option in the list, so user can select Global option and add himself phone number without validating the number.

https://intl-tel-input.com/examples/country-sync.html
In this case, if the user selects a country that is not in the list, the phone number input will show the Global Flag and the user will be able to add the phone number without validating the number instead of getting an error. `No country data for 'bv'`

### Actual behaviour
Users are not able add telephone number if they country is not on the list.

**Comment by jackocnr** [comment]
Can you give a specific example of the problem, for the user? What country are they from, and what number are they trying to enter, and what problem are they having?

**Comment by minhluan259** [comment]
Here is a specific example:

https://github.com/user-attachments/assets/560ddf9d-a843-44a7-ab24-3c7efee887ad

**Comment by jackocnr** [comment]
You're getting an error because you're calling `setCountry` and passing an unsupported country code. There is a [specific list of criteria](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intl-tel-input/data.ts#L3-L6) required for us to support a country, and Antarctica doesn't meet that criteria. If you want to have those countries in your separate Country list, then before calling `setCountry`, you'll need to check that it is a supported country code (e.g. using `getCountryData`), and if it's not supported, you can call `setCountry()` without passing an argument, to select the empty state (Globe icon).
