### ISSUE TITLE
Can we get a list of all area codes? Formatting gets messed up when a number does not start with the correct area code.

### ISSUE THREAD

**Issue by nidamunir-extreme** [jackocnr/intl-tel-input#1907]
### Plugin version
e.g. v25.2.0 (please try latest version)

### Steps to reproduce
Can we get all area codes of a country? The input only formats a number with valid area code, and there is no way to notify the users that you started the number with incorrect area code. 

Output of `getSelectedCountryData()` does not include area codes
![Screenshot 2024-12-30 at 19 42 39](https://github.com/user-attachments/assets/c21d06e5-1856-452e-ab30-d23e3e7099ec)

It does not format the US number when I start with 1. Is there a way to tell users, that you started the number with incorrect digit/are code?

![Screenshot 2024-12-30 at 19 56 40](https://github.com/user-attachments/assets/030e83b2-1403-45e1-a77f-36f0fc590356)

Formats correctly if I don't start with 1

![Screenshot 2024-12-30 at 19 56 49](https://github.com/user-attachments/assets/f5b8c547-2e5c-4ce1-9a76-68be8fbdab60)

Formatting is incorrect when you don't start a number with 3. In Pakistan, phone numbers start with 3

![Screenshot 2024-12-30 at 20 01 32](https://github.com/user-attachments/assets/f6305a20-2a13-42a3-a251-3828b56cb932)

![Screenshot 2024-12-30 at 19 59 18](https://github.com/user-attachments/assets/ccd267fb-b94a-462e-9b6c-b0a97725436c)

Correct formatting when I start the number with 3.

![Screenshot 2024-12-30 at 19 59 29](https://github.com/user-attachments/assets/a89f9d91-abad-4432-a3fc-2621990221cf)

**Comment by jackocnr** [comment]
I understand your request, but unfortunately, it's not currently possible, and on reflection, I don't think I want to add this feature. We don't store the area codes for the primary territory for a given dial code (e.g. USA) because in some cases, this would involve listing hundreds of area codes, which would increase the plugin filesize, and require significant maintenance time. IMO this cost is not worth it for the use case of when the user accidentally types an incorrect area code, and then they don't get the automatic format-as-you-type feature. I would say this is an acceptable compromise, and I would recommend to just validate the form field on blur/submit as usual and show an error message at that point.
