### ISSUE TITLE
Paste into phone field adds "ext." when there is none.

### ISSUE THREAD

**Issue by pablotola** [jackocnr/intl-tel-input#258]
When pasting a phone number "561 228 1612" into the input and allow extension is true, the plugin automatically formats the number which is good but adds an empty extension, so the phone number ends up like this: "(561) 228-1612 ext."

How do you prevent that from happening.

**Comment by jackocnr** [comment]
Thanks for reporting this. I think it would be fixed by passing `true` as the third option to the `_handleInputKey` call on line 489 of src/js/intlTelInput.js, but this needs testing, and if it works, it needs commenting and building and checking the tests still pass (and ideally adding a new test) and then doing a pull request, which unfortunately I don't have the time to do right now, but I'm very open to other people contributing this work!

**Comment by jackocnr** [comment]
Fixed in v7.0.0
