### ISSUE TITLE
How to keep the input data when the page is reloaded?

### ISSUE THREAD

**Issue by brunoDegaspare** [jackocnr/intl-tel-input#369]
When the page gets posted to the server with an invalid number typed by the user, the invalid number should remain visible, so the user can correct it. How can I keep the typed phone number after the is reloaded?

**Comment by jackocnr** [comment]
What you do with the page after a reload is entirely up to you - this has nothing to do with the plugin. You will need to find a way to store the submitted value (or return it from the backend) and then re-display it to the user again.

**Comment by theyuv** [comment]
Hello, thanks for the plugin, very cool.
I store the submitted value and try to re-display it to the user by placing in the `$("#phone")` element's `value `attribute. However, this value is not directly displayed. It undergoes some formatting (eg: turns letters into numbers) and then gets displayed.
How would I display the value attribute of the element (eg: disable the formatting that's done to it by the plugin)?

**Comment by theyuv** [comment]
For now, after initializing the plugin, I run a callback function that updates the current value of my phone element from the default value (in the value attribute of the phone element):
```
$("#phone).intlTelInput({...}).done(function(){
            var defaultValue = $("#phone").prop("defaultValue");
            if (defaultValue)
                 $("#phone").val(defaultValue);
});
```
Any feedback on a better solution would be appreciated.
Again, I'm trying to disable the automatic formatting done in the "_updateValFromNumber" function.
This is because I am doing all of my validation server side and would like to return to the user the same exact value that he submitted.

Thank you.

**Comment by jackocnr** [comment]
Hi @theyuv, you raise a good point. I have added a new option called `formatOnInit` which is set to `true` by default, but you can disable it for your use case. Released in v8.4.0.

**Comment by theyuv** [comment]
Great, thanks. I'm happy to have been able to contribute.
Cool plugin.
For now, I only use the placeholder and flag selection features of it.

**Comment by shahid1579** [comment]
@theyuv  @jackocnr 
I am keeping the number when page is loaded but how can i show valid or invalid when page load.
when i use .done its giving error done is not defined.
I will very thankful to you.
