### ISSUE TITLE
Question: Should I concatenate utils.js with other js files

### ISSUE THREAD

**Issue by theyuv** [jackocnr/intl-tel-input#375]
Hello again,

If I concatenate all of my js files for production, would you recommend concatenating the utils.js script into my one js file as well?
Then what would I pass in the "utilsScript" option? The path to the full, concatenated js file? Does this mean that the entire js file would then be reloaded?
Or is it better to not concatenate the utils.js file and just load it separately? (I try to not load more than 1 js file per page because I was told this is good practice in terms of page loading times).

Thank you.

**Comment by jackocnr** [comment]
Hi there. No do not concatenate utils.js into your main production build. You should load it separately using the `utilsScript` option. This is fine for page loading times because it is lazy loaded only when the plugin is initialised, and it makes sure the rest page has finished loading first as well, before it starts.
