### ISSUE TITLE
Country Code Issue for some countries

### ISSUE THREAD

**Issue by vasnakos** [jackocnr/intl-tel-input#443]
I have an issue with the country codes for countries like American Samoa which have the '+1' country code  of US, followed by 3 digits (684) of the country.
When i use the `intlTelInput("getSelectedCountryData").dialCode` event it returns +1684, but when i use the `intlTelInput("getNumber")`  event it returns '+1' followed by the number I typed (684 is missing).

**Comment by jackocnr** [comment]
What initialisation options are you using? And what number are you typing in the input?

**Comment by vasnakos** [comment]
I'm using the default initialization options and as for the number i type random digits (10 digits).

**Comment by jackocnr** [comment]
Yes that is correct. So by default, nationalMode is enabled, which means the user is expected to type the full national number (the full number that you would have to dial in that country). Does that make sense?

**Comment by jackocnr** [comment]
Hmm perhaps this is inconsistent. If they select United States, the dropdown option says +1, but if they select America Samoa, the option says +1684. Perhaps it would be clearer if the America Samoa option also just said +1? (I think this would be an easy change).

**Comment by vasnakos** [comment]
I think the problem is that while the `intlTelInput("getSelectedCountryData").dialCode` returns +1684, the `intlTelInput("getNumber")` returns +1 followed by the number the user typed. It doesn't add the whole country dial code. It might be preferable to add the whole dialcode to the input?

**Comment by jackocnr** [comment]
FYI the reason those two methods behave differently is because `getSelectedCountryData` just fetches our own meta data, and `getNumber` calls libphonenumber and passes it the input value and the country code (e.g. "as" for America Samoa) and it composes the formatted number.

Hmm I've changed my mind about my proposed solution because +1684 is the international dial code for AS, so it doesn't make sense to change it to just +1.  Also I think it's fine to expect people to enter their full national phone number (inc 684) because that is what they have to dial anyway. You should just check it with `isValidNumber` to make sure they have done.

If you want to add the whole dial code to the input, you can set `nationalMode` to false.

I'm going to close this for now - let me know if you disagree with what I've said and you think that the user experience is currently confusing.

**Comment by vasnakos** [comment]
Many Thanks man :)
