### ISSUE TITLE
Add support for isPossibleNmber

### ISSUE THREAD

**Issue by asuraphel** [jackocnr/intl-tel-input#446]
I'm using int-tel-input to validate phone numbers but I'm getting invalid for numbers that are actually valid. I tried to see if the if the problem exists in `libphonenumber` by going over the demo site and it does. However `isPossibleNumber()` returns true for the number i'm trying to validate. For our case we have no choice other than using  `isPossibleNumber()`. Can you add support to it? 

Thanks!

**Comment by jackocnr** [comment]
If the number is valid and libphonenumber's `isValidNumber` is returning false, then that sounds like a bug! Please file an issue with them.

**Comment by asuraphel** [comment]
Thanks for the swift response, @jackocnr. But can you additionally add support for `isPossibleNumber`?

**Comment by jackocnr** [comment]
No I'm sorry but utils.js is already over 200KB, and there's no way I'm going to add any extra weight to that just because of one little bug! You're welcome to modify src/js/utils.js  yourself and build your own custom version of libphonenumber tho.

**Comment by asuraphel** [comment]
I understand your point. However the bug is not that little :). It renders the whole plugin unusable for us at the moment b/c we don't want to ship a form that tells users that their number is invalid when is valid. It's better for us to get false positives instead.

**Comment by rjoo** [comment]
If anyone needs, I've forked and rebuilt [utils.js](https://github.com/rjoo/intl-tel-input/tree/master/build/js) for `isPossibleNumber` support.

**Comment by jackocnr** [comment]
Thanks for doing that @rjoo. Interestingly, that compiled file looks to be the same size as mine! Still, I would like to avoid adding anything that is not completely necessary. If this bug is going to be fixed up stream, then I'd like to just wait for that. @asuraphel did you file a bug with libphonenumber? Do you have a link to the issue?

**Comment by rjoo** [comment]
No problem. Totally valid reason for not wanting to include it. In my case, client requested a more lenient way of validating phone numbers and specifically called out libphonenumber's `isPossibleNumber`.

Thanks for this great plugin, btw!

**Comment by plocket** [comment]
My team would also appreciate a more lenient way of validating a number in this library to allow people in critical situations to still enter their information in. No offense to rjoo, but that fork hasn't been updated in years.

Since libphonenumber already has that validation functionality built in, can you just use that, @jackocnr? No need to build any new validation. It would allow for more flexible validation, which can be important for people in critical situations who don't have the time to file a bug report and yet still need the app to clue them in if they've done something totally wrong.
