### ISSUE TITLE
sprite-retina-mustache.scss - Invalid CSS when running compass

### ISSUE THREAD

**Issue by kfiroo** [jackocnr/intl-tel-input#447]
Hey,
We are getting an error when running compass

This is the error:
`error app/assets/bower_components/intl-tel-input/grunt/tmpl/sprite-retina-mustache.scss (Line 10: Invalid CSS after "...m-width-maps: (": expected ")", was "{{#items}}{{str...")`

Coming from this line: 
`https://github.com/jackocnr/intl-tel-input/blob/master/grunt/tmpl/sprite-retina-mustache.scss#L10`

Any ideas?

Thanks,
Kfir

**Comment by jackocnr** [comment]
Thanks for pointing this out. That file should be renamed to `sprite.scss.mustache` because it is actually a mustache template. As a note: when we make that change, we need to update the reference here: https://github.com/jackocnr/intl-tel-input/blob/master/grunt/sprite.js#L20

Unfortunately I'm too busy to do this myself right now, but I would be happy to accept a pull request!

**Comment by kfiroo** [comment]
@jackocnr Hey, Thanks for the response!
I will create the PR asap :)

**Comment by kfiroo** [comment]
@jackocnr done. [450](https://github.com/jackocnr/intl-tel-input/pull/450)

**Comment by jackocnr** [comment]
Thanks!
