### ISSUE TITLE
Add new option - custom CSS class for the iti-container

### ISSUE THREAD

**Issue by girtsl** [jackocnr/intl-tel-input#468]
Please add new option - a way to add a custom CSS class (or classes) to the iti-container.

For some input instances I would like to hide the dial codes - to only display the list of countries and flags. 
This can be easily accomplished by setting a CSS class to the input element's container and having a CSS rule like this one - `.my-custom-class { .dial-code{display: none;} }`. 
However, this doesn't work if I want to display the input in a modal and have to set the `dropdownContainer` to `body` - that way all instances would be affected.

Maybe I'm approaching this in the wrong way and there is a better way to do this?

**Comment by jackocnr** [comment]
When you're not using `dropdownContainer` you can just set your custom class on your own container surrounding the input.

When you are using `dropdownContainer`, instead of setting it to body, instead create a div at the end of the body, give it your custom class, and set `dropdownContainer` to use that div.

Does that work?

**Comment by girtsl** [comment]
Works for me, thanks!
