### ISSUE TITLE
Russia country code wrongfully converted

### ISSUE THREAD

**Issue by 23stripes** [jackocnr/intl-tel-input#492]
### Steps to reproduce
1. Input +79123456789 (Russian number)
2. _Save_

### Expected behaviour
The first digit (7) shouldn't be converted to 8

### Actual behaviour
Plugin displays it as `8 (912) 345-67-89` despite being stored as `+79123456789`

**Comment by jackocnr** [comment]
The issue is when you initialise the plugin (with nationalMode: true) with the input value as `+79123456789` then it changes the number to `8 (912) 345-67-89`.

We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, and if you click on their JavaScript demo, enter that number and submit, you will see that is how they format the number for "national format". If you think this is wrong, you will need to file an issue with them.
