### ISSUE TITLE
Set number to E164 only

### ISSUE THREAD

**Issue by ilyasmuyiwa** [jackocnr/intl-tel-input#497]
[blank]

**Comment by ilyasmuyiwa** [comment]
Great job,
Please i am new to javascript. How do i setnumber to E164 only without spacing between the numbers. I want to do something like this
 jQuery("#telephone").intlTelInput("setNumber", "+447712342828", intlTelInputUtils.numberFormat.E164);
I want it to return +447712342828 without any space

Pardon my ignorance, I am newbie

Thanks

**Comment by jackocnr** [comment]
Hmm you cannot currently do this with `setNumber`. I would be open to a pull request to add this feature tho. So we would add an optional 2nd argument, which if specified we would use that, otherwise we use the current logic - format according to the value of the `nationalMode` option.

In the mean time you can just set the input value to the given number: `jQuery("#telephone").val("+447712342828").keyup();`  - you need the keyup to update the flag.

**Comment by ilyasmuyiwa** [comment]
Thanks a lot Jack. I really appreciate.
I used jQuery("#telephone").val("+447712342828").keyup();   but it still put spaces. The result 
+447712 342828 and i want +447712342828. Is there a way for me to achieve this

Thanks a lot.

**Comment by jackocnr** [comment]
We don't have format-as-you-type in the plugin anymore. Please can you check you're using the latest version?

**Comment by jackocnr** [comment]
On second thought, any formatting we allow you to do with `setNumber` should be consistent with what happens on initialisation. Also I don't think there's any point in allowing you to specify the format yourself - I think you just need a boolean to say whether you want the number to be formatted or not. So instead I think we should rename the initialisation option `formatOnInit` to `formatOnDisplay` (boolean) and check that on `setNumber` as well as on initialisation.

**Comment by jackocnr** [comment]
Implemented in v10.0.0.
