### ISSUE TITLE
Show separateDialCode  but us National format?

### ISSUE THREAD

**Issue by Mike-Dunton** [jackocnr/intl-tel-input#518]
I would like to be able to show the country code next to the flag but format the number as national format. 

[ Flag +1] (201) 555-0123

From what I can tell my to two current options are 

Option One
![screen shot 2016-12-08 at 12 2 58 pm](https://cloud.githubusercontent.com/assets/3373565/21019399/4d36861c-bd3e-11e6-8333-4ff7d58d5fa2.png)

Option Two
![screen shot 2016-12-08 at 12 5 52 pm](https://cloud.githubusercontent.com/assets/3373565/21019511/b2df18e4-bd3e-11e6-817d-db4e00c9ef48.png)

 
### Initialisation options
Option one
```
{
    allowDropdown: true,
    initialCountry: 'us',
    onlyCountries: ['us', 'ca'],
    utilsScript: 'utils.js'
}
```

Option Two
```
{
    allowDropdown: true,
    initialCountry: 'us',
    onlyCountries: ['us', 'ca'],
    separateDialCode: true,
    utilsScript: 'utils.js'
}
```

Is there a way to do formatting from option one and flag and dialcode from option two?

**Comment by jackocnr** [comment]
No it's not possible to display the national number next to the international dial code because in some countries the national number contains extra digits, and so it doesn't make sense to put it next to the international dial code.

For example in the UK, an international number might be +44 7773 333333, but the national version would be 07773 333333 (note extra 0), and it wouldn't make sense to display the +44 next to that number.

**Comment by Mike-Dunton** [comment]
@jackocnr what about custom formatting on a per country basis? Is that something I'd have to update with the libphonenumber utility script?

**Comment by jackocnr** [comment]
Yeah we use libphonenumber for formatting, so you'd have to speak to them about handling custom formats. This is actually something I wanted from them a long time ago, but unfortunately they weren't interested in adding it at the time. Who knows what the situation is now tho...
