### ISSUE TITLE
Space after country dial code

### ISSUE THREAD

**Issue by lukaszflorczak** [jackocnr/intl-tel-input#539]
Hi. Is it possible to add a space after the country dial code?

For example: ```+48 123456789```

**Comment by jackocnr** [comment]
Did you try the `formatOnDisplay` option?

**Comment by lukaszflorczak** [comment]
Yes, I tried. But I don't see a option to change the country dial code by adding a space char after it.

**Comment by jackocnr** [comment]
There's no option to format it exactly as you say - because that's not a standard format. We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, and so can only offer the formats they provide.

For the number you specified, you should get `+48 12 345 67 89` (if you set `nationalMode` to false).
