### ISSUE TITLE
flags.png missing in the final build

### ISSUE THREAD

**Issue by arete** [jackocnr/intl-tel-input#546]
Hi,
i use intl-tel-input in the my simple html5 project with bower and gulp.
I have add this lbrary to my project via bower.
How to i try to test the application localy with `gulp serve` work fine and i see the nation logo.
But if i try `gulp build`  the deply is missing the image flags.png.
How to fix this problem ?

**Comment by jackocnr** [comment]
Well the images you need are in build/img/ so it sounds like a problem with your Gulp configuration. I'm afraid I'm not familiar with Gulp, so I can't be of help.

**Comment by taharedape** [comment]
@arete did you manage to fix this issue? I'm having the same with grunt build

**Comment by jackocnr** [comment]
@arete and @taharedape: please can you describe the problem in more detail. What exactly is the problem? Where are you expecting the flags.png file to be?

**Comment by taharedape** [comment]
@jackocnr Thanks for the follow up. 

Well, we both are using some builders which will minify/uglify our projects into distribution folder for production deployment. 

basically the images in the library are pointing at the img folder which of course does not include the flag images and since the bower components (where the libraries are) are concat with all other js files into one, there is no pointing to it and therefore, it's not found. 
Nevertheless, I fixed the issue by providing the url for the flags (CDN) as below: 
.iti-flag {background-image: url("https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/11.0.4/img/flags.png");}
Thanks

**Comment by jackocnr** [comment]
Yeah, as per the Getting Started section of the readme, you need to override the image paths in the CSS.
