### ISSUE TITLE
A blank space passes format validation

### ISSUE THREAD

**Issue by JuanJo4** [jackocnr/intl-tel-input#559]
Hey,
 
### Steps to reproduce
I've checked this [on libphonenumber library](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) and it validates correctly a blank space. However, if I tried a blank space [on intl-tel-input](http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html)  it passes the format validation.

### Expected behaviour
Should said it's an invalid phone number.

### Actual behaviour
It passes the format validation as a valid phone number.

### Initialisation options
I don't have this right now, but I'll find it if it needs to.

Thanks!

**Comment by jackocnr** [comment]
I just tested this, and calling `isValidNumber` returns false for just a space in the default setup (nationalMode: true and US flag selected). What options are you using, and what flag do you have selected?

**Comment by JuanJo4** [comment]
I'm just found this happens because the trim on this function

`// on blur: validate
telInput.blur(function() {
  reset();
  if ($.trim(telInput.val())) {
    if (telInput.intlTelInput("isValidNumber")) {
      validMsg.removeClass("hide");
    } else {
      telInput.addClass("error");
      errorMsg.removeClass("hide");
    }
  }
});`

Is there a special reason that obligates to trim the string? I believe that I would need to use a workaround to validate a blank space.

**Comment by jackocnr** [comment]
The reason I put that in the demo code is because I don't think it makes sense to mark an empty input as invalid. I hate it when I tab through a form and all the inputs get errors. I think that there is no point in validating an empty input - obviously the user has chosen to not put anything there (and I consider it empty if they just put a space - because that's obviously not a phone number).

But it's a preference thing, so if you want it to show an error on your website then you can simply remove that trim condition!

**Comment by JuanJo4** [comment]
Yep, I get your point. Thanks for the quick responses.
