### ISSUE TITLE
Feature suggestion: hidden input

### ISSUE THREAD

**Issue by HawkonDK** [jackocnr/intl-tel-input#575]
Option for enable country code to be a part of the input when use PHP `$_POST` to grab the number

I know you have `getNumber` but I mean a option so you don't need a ajax part to grab the data.

example make it possible to just do `$_POST['contryCode']` by generate a hidden input. Just like countrySync

**Comment by HawkonDK** [comment]
If you put this in your countrySync.js it will work

```
// get the country data from the plugin
var countryData = $.fn.intlTelInput.getCountryData(),
  telInput = $("#phone"),
  addressDropdown = $("#address-country");
  CountryCode = $("#CountryCode");

// init plugin
telInput.intlTelInput({
  utilsScript: "../../build/js/utils.js" // just for formatting/placeholders etc
});

// populate the country dropdown
$.each(countryData, function(i, country) {
  addressDropdown.append($("<option></option>").attr("value", country.iso2).text(country.name));
});

// set it's initial value (iso2)
var initialCountry = telInput.intlTelInput("getSelectedCountryData").iso2;
addressDropdown.val(initialCountry);

// set it's initial value  (dialCode)
var dialCodeCountry = telInput.intlTelInput("getSelectedCountryData").dialCode;
CountryCode.val(dialCodeCountry);

// listen to the telephone input for changes (iso2)
telInput.on("countrychange", function(e, countryData) {
  addressDropdown.val(countryData.iso2);
});

// listen to the telephone input for changes (dialCode)
telInput.on("countrychange", function(e, countryData) {
  CountryCode.val(countryData.dialCode);
});

// listen to the address dropdown for changes
addressDropdown.change(function() {
  telInput.intlTelInput("setCountry", $(this).val());
});

```

**Comment by jackocnr** [comment]
Yeah I quite like this idea, except instead of the hidden input storing just the country dial code, I think it should store the whole standardised international number, like in the [hidden input example](http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/hidden-input.html), because then that one field contains everything you need (you only have to store one value in your database, and you only have to pass one value back to your frontend when displaying the number again). We could call the new option something like `hiddenInput` and you would set it to a string that you wanted to be it's `name` attribute, so you know what to expect on your backend.

Unfortunately I don't have time to implement this myself right now, but I would be open to a pull request to add this functionality 👍

**Comment by jackocnr** [comment]
Added in v12.0.0.
