### ISSUE TITLE
Not saving country selection for toll-free #s

### ISSUE THREAD

**Issue by hornetnz** [jackocnr/intl-tel-input#581]
I noticed that toll-free #s are not saving the selected country code, which I thought was the expected behavior according to issue #503.

The isValidNumber requires a country code, so any checks against just a # will fail. Should validity checks be getNumberType='TOLL_FREE' OR isValidNumber?

### Steps to reproduce
1.  Select US
2.  Enter 800-345-1234
3.  Save
4.  Reload the form w/ user data
5.   Country is blank, field shows as invalid

**Comment by jackocnr** [comment]
So that number does validate successfully, but you're right, if you init the plugin with `+18003451234` as the value then it does not automatically select the flag. It cannot do this because 800 is a regionless NANP code (https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L48) and if there's a chance your users might enter a regionless number like this, then you need to store the country code (e.g. "us") as well as the number, and then set the country during initialization. Does that make sense?

**Comment by hornetnz** [comment]
That make sense. But should isValidNumber add a check for the NANP codes? Being it IS a valid number, but if country isnt passed it doesn't like it.

**Comment by jackocnr** [comment]
Oh you're right, there's currently a bug where calling isValidNumber throws an exception: `Uncaught TypeError: Cannot read property 'dialCode' of undefined`. I don't think the solution is to check for NANP codes - because the libphonenumber demo says `+18003451234` is a valid number without providing a country code, so I think the bug is somewhere else - probably we make an assumption somewhere that there is a selected country.

Thanks for bringing this to my attention. Unfortunately I don't have time to look into this right now, but I would gladly accept a pull request for a fix.

**Comment by hornetnz** [comment]
Not sure if this is related, if not lemme know and I'll create a separate ticket for it...

Can you verify that getNumberType is working for toll-free numbers? ie: Im checking 800-780-6310 and getting back -99. But testing the same # on [googles phonelib](url=https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) is showing it as a toll-free type.

**Comment by jackocnr** [comment]
I see, yes I get that error if I initialise the plugin with the input `value="+18003451234"` and then call `getNumberType`. I think everything will fail in this situation because technically it's a broken state - if we have no international dial code in the input (e.g. +1), then we need a selected country to get a full number.

I think that when nationalMode is enabled, we always need to have a country selected, else we're in a broken state. So if the plugin is initialised with nationalMode=true and an input value with a regionless NANP number, and no initialCountry option, then we should default to the US flag. This will fix these two issues, and probably lots more.

Does that make sense to you?

**Comment by hornetnz** [comment]
Yes I think so. Thanks for the explanation!

**Comment by jackocnr** [comment]
I forgot to say: unfortunately I don't have time to implement a fix myself right now, but would be open to a pull request!

**Comment by jackocnr** [comment]
Fixed in v11.1.5.
