### ISSUE TITLE
Autocomplete is set to off

### ISSUE THREAD

**Issue by flourishdna** [jackocnr/intl-tel-input#587]
### Steps to reproduce
N/A. I have tried adding autocomplete="On" to input field manually but for some reason, it is getting overwritten.

### Expected behaviour
Input autocomplete from off to on

### Actual behaviour
The input autocomplete is currently set to off

### Initialisation options
```
autoHideDialCode: false,
autoPlaceholder: true,
nationalMode: false,
separateDialCode: true
```

**Comment by jackocnr** [comment]
If you search this repo for "autocomplete" you will find that we force disable it to prevent problems: https://github.com/jackocnr/intl-tel-input/blob/ebd0cbe02c7dbdc8e1ae38a491c645241a199305/src/js/intlTelInput.js#L209

**Comment by julien-c** [comment]
@jackocnr First, thanks for your great module which I am using in production. I wanted to concur that having an (even imperfect) `autocomplete` is important for us: I'm turning it on again after instantiating my tel input with your plugin.

I don't mind having a few inconsistencies as much as removing the functionality for the majority of users who are not going to have an issue. And in my testing (in modern evergreen browsers) I haven't actually been able to expose an issue (I guess browsers now pick up the `change` event from autocompletes?).

Maybe expose this as an option? Just my 2 cents.

**Comment by jackocnr** [comment]
It's not a problem with the browser reacting to changes caused by the plugin, it's a problem with the plugin reacting to changes caused by the browser (namely input value changes caused by autocomplete, which dont trigger and standard cross-browser events that we can listen for).

If the user is just quickly tabbing through inputs, filling in a form, and tabs to the phone number input and ignores the flag and just autocompletes their usual phone number and then submits the form, if the dev uses `getNumber` (which is strongly advised), then the number will be assumed to be for whatever flag happens to be selected, and so there's a good chance the resulting number will be wrong.

IMO disabling autocomplete is a small price to pay for having the plugin in a consistent, stable state.

**Comment by ibarral** [comment]
Chrome 63 is ignoring autocomplete="off", and tries to suggest previous user entries.

The only solution is to assign a random string to the attribute, for example:

`autocomplete="nope"`

Source: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

I think that we'll need a fix to that :(

**Comment by jackocnr** [comment]
Thanks for reporting this @ibarral. I think this is worth tracking in it's own issue - would you mind copying your comment into a new issue? Also I would be open to a PR to make this change. Thanks.

**Comment by ibarral** [comment]
ok! I just did that ;)

thanks for your awesome work!
