### ISSUE TITLE
When i select Canada flag and type number without 204 country code, flag automatically change into USA flag

### ISSUE THREAD

**Issue by byrnecode** [jackocnr/intl-tel-input#710]
### Expected behaviour
If you select Canada country flag it should stay as Canada after inputting phone number.

### Actual behaviour
If you select Canada country flag it is changing to USA after inputting phone number. (unless I type 204 in the beginning, which is not a requirements since I'm using international mode)

### Initialisation options
using utilsScript

**Comment by jackocnr** [comment]
You said you're using "international mode" - does that mean you've set "nationalMode" to false?

What exactly is in the input when the flag changes to US?

**Comment by byrnecode** [comment]
Sorry if I wasn't clear. No I did not set the "nationalMode" to false. I am getting the phone value in a hidden field through 'getNumber'. 

"What exactly is in the input when the flag changes to US?" -When I select Canada as country flag, whenever I type at least 3 numbers, whatever number, the country flag turns to USA. Not unless I type 204 at the beginning, then it will stay as canada. In fact it is happening on your demo pages at https://intl-tel-input.com/. I'm not sure if this is designed like this, since Canada and US have the same country code/exit code (+1 or 011), but I'm pretty sure I wan't it it to stay as Canada if the user select that.

Several people have already posted this issue on forums like stackoverflow, but didn't get any answers, so I decided to post it directly here.

**Comment by jackocnr** [comment]
Again, please tell me exactly what you're typing when it changes to America.

**Comment by byrnecode** [comment]
Oh man, what so hard to understand on my explanation? I am typing any numbers
**When I select Canada as country flag, whenever I type at least 3 numbers, whatever number, the country flag turns to USA.**

**Comment by byrnecode** [comment]
Even the issue title itself is already self-explanatory.. Sorry but you are being difficult.

**Comment by jackocnr** [comment]
Haha, I'm sorry if I'm coming across as rude, but actually I'm just short on time, and I need you to be more specific in order for me to debug the issue you're seeing. It is mind boggling to me that you **still** have not provided the specific information I have ask for, but nevertheless I will try to guess what your problem is with what information you have provided.

If you go to the demo page, select Canada and type in a [Canadian area code](https://www.wikiwand.com/en/Telephone_numbers_in_Canada) (e.g. `403`), then the flag should stay as Canada. If you type in an American area code (e.g. `702`) then it will change to America. Does this answer your question?

**Comment by byrnecode** [comment]
Sorry man, it is also boggling me **how you don't get** all of that explanation that I already provided. 

**What you ask:** "please tell me exactly what you're typing when it changes to America"
**I answered:** "I am typing any numbers, whenever I type at least 3 numbers, the country flag turns to USA"

How is that not answering your question? Sorry I'm not trying to argue here but how are you not getting it? Seriously man I already laid it out on **expected behaviour** versus **actual behaviour**

Basically what I want is that when the user select Canada, the country flag won't change to USA, even if the user don't have to type the canadian country code.

What's happening in your forms is, if I select canada, then type let's say 123, the country flag is changing to US. I don't want that as I want to capture it as what country flag the user **selects**. I get what your trying to say that I should type the canadian country code first in order for it to stay canada, but you can't control users like that, what if a user just type any number without including country code for canada?

**Comment by jackocnr** [comment]
> Basically what I want is that when the user select Canada, the country flag won't change to USA, even if the user don't have to type the canadian country code.

I don't think this makes sense. If the user types a Canadian number, what is the harm in keeping the flag updated? For me it's the same as if the user types +44 in the input - it doesn't make any sense to leave America selected - it makes sense to change the flag to UK, to reflect the user's action, and to keep the plugin in a consistent state.

> what if a user just type any number without including country code for canada?

They will notice that the flag keeps in sync with whatever they type, so they are free to type a random number if they want, and they will get a random flag, and if when they're done playing, they enter a Canadian number, they will get a Canadian flag!

**Comment by byrnecode** [comment]
Your explanation didn't really answer the issue at hand. I can't believe you just deliberately keep ignoring the real issue, and all that explanation that I did.

Here's the thing, I can understand if you type +44 while USA is selected, it will change to UK. I totally understand that because it is what it's supposed to do. I understand that if you include the country code, it will change to whatever country it is matching.

##What you don't understand is
If you type any random number when Canada is selected, it is changing to USA. **But** this same behavior is **not happening to any other countries**.

I encourage you to open the demo page and replicate this:

Choose country flag USA, type in 222, did the country change to anything else? NO
![image](https://user-images.githubusercontent.com/14091662/37498363-e37f13ec-28f8-11e8-8808-bc41e7946e62.png)

Choose country flag UK, type in 222, did the country change to anything else? NO
![image](https://user-images.githubusercontent.com/14091662/37498378-fe21beac-28f8-11e8-9197-426b81de095a.png)

Choose country flag Afghanistan, type in 222, did the country change to anything else? NO
![image](https://user-images.githubusercontent.com/14091662/37498397-1ca90f1a-28f9-11e8-9560-4c4813fe5186.png)

**Now** choose country flag Canada, type in 222, did the country change to anything else? **oh wow yes it changed to USA, which is all the point I'm trying to make**
![image](https://user-images.githubusercontent.com/14091662/37498472-8483b5ea-28f9-11e8-8b02-7a674b31c3ec.png)
![image](https://user-images.githubusercontent.com/14091662/37498473-8bd41808-28f9-11e8-9be9-f2f81c7b0805.png)

Now does that make any sense? If you still didn't get it despite me putting all the time and effort explaining it, then I give up. I feel like reporting an issue is a hopeless endeavor from the start. You keep mentioning that you got a short time to answer issues, is a sign that you really don't want to bother with this from the start. I can understand that. But please don't just deliberately keep ignoring people that submits an issue by not trying to understand the whole context just because _you don't have the time_.

Also closing tickets without waiting on other user reply, is irl just like suddenly turning your back on people even if your conversation has not yet ended. **That's not how issues are being solve in this open-source world my friend.** Good luck to this project and have a nice day!

**Comment by jackocnr** [comment]
Thank you for finally providing what I asked for - it is helpful in this case to deal in specifics - let me explain why. Without meaning to be rude, just for the sake of clarity: when you said that "selecting Canada and then typing any 3 numbers always changes it to America", that is incorrect. If you type one of the many Canadian area codes, it will stay on Canada. If you type `787` it will change to Puerto Rico! And there are lots of other examples too (Jamaica, Trinidad, Virgin Islands etc).

The way it works is: if you have a NANP ([North America Numbering Plan](https://www.wikiwand.com/en/List_of_North_American_Numbering_Plan_area_codes)) country flag selected (US, Canada, Puerto Rico etc), then we update the flag based on the first 3 digits you type (the area code) because for these countries, that area code is actually part of the international dial code (e.g. +44) in that it does dictate which country the number is for. So +1403 is a Canadian number (or any of the other area codes in that link I sent earlier - they are all Canadian numbers), +1787 is Puerto Rico, and there are a bunch more for other countries, and then anything else defaults to America, because America has by far the most of these area codes (hundreds I think), and if a user types an unrecognisable area code, it seems like an acceptable compromise to default to America. (also note that new area codes are being assigned every year, and so there's a risk of being out of date, in which case the safest bet is to default to America).

So in your case, you were typing 222, which is not a valid NANP area code, so it defaulted to America.

So as I see it, there are two points here which you may or may not agree with, and I'm open to your feedback on:

The first is: do you think it's acceptable to change the flag when a NANP country is selected and the user types the area code of another NANP country? As I have stated, I think this makes sense because the area code is part of the intl dial code, so it's the same as typing +44.

The second is: do you think it's acceptable to default to the country with by far the most area codes when the user types an unrecognised area code? IMO if you accept the first argument, then this one follows, because you're accepting that it's ok to change the flag based on the area code, and in this case, the user is typing an invalid area code, so my response is: firstly this is an edge case that we shouldn't worry about too much, and secondly, defaulting to America makes the most sense because as I say, America has by far the most area codes assigned to it, therefore it's our best guess for what the user is intending.

What do you think?

**Comment by byrnecode** [comment]
Thank you, that was the explanation I was looking for. I clearly understand about the changing of flag based on area code. What bothered me was the random unrecognized area code, which you already explained perfectly. 

Just to give you an idea on why I'm keen on this, our process requires that if a user selects a country, well be getting that country value, regardless of the random unrecognized area code. So it was weird for me that it was changing to USA even if the number was random. Now that I know the reasons, I guess I'll just be writing a custom code to get what user selects.

Thanks for the help, I apologize if I sounded rude at times. I'm actually a cheerful person. I just really wanna solve this one. Have a good day!

**Comment by jackocnr** [comment]
Great, glad we're on the same page.

> Now that I know the reasons, I guess I'll just be writing a custom code to get what user selects.

👍 

> I apologize if I sounded rude at times

No worries man, we've all been there. Again, I apologise for being short with you. Take it easy ✌️
