### ISSUE TITLE
Add new dial(area) code for Jamaica - 658

### ISSUE THREAD

**Issue by abbagria** [jackocnr/intl-tel-input#727]
### Steps to reproduce
1.  Click on country dial code drop-down, search for "Jamaica".

### Expected behaviour
For Jamaica 2 dial codes should show in the country dial code drop-down, both ,the current one i.e. 876 and the new one i.e. 658.
Link for more information: http://jamaica-gleaner.com/article/lead-stories/20170828/call-658-jamaica-gets-additional-area-code-10-digit-dialling-becomes

### Actual behaviour
Currently, only one option shows for Jamaica (Jamaica +1876)
![image](https://user-images.githubusercontent.com/22320339/39241677-5fc24570-48a5-11e8-88ec-9be8b4d94754.png)

**Comment by jackocnr** [comment]
Thanks for reporting this. We definitely need to add support for this. Though actually we wont display multiple area codes next to Jamaica in the list, instead we'll just display `+1`, like we do for other [NANP countries](https://en.wikipedia.org/wiki/North_American_Numbering_Plan) e.g. Puerto Rico.

I welcome a PR for this change - it will just be a case of tweaking the meta data in src/js/data.js for Jamaica, using the format for Puerto Rico.

**Comment by jackocnr** [comment]
Thanks. Merged. Will be in next release.

**Comment by abhishekbagria** [comment]
Thank you for making the change. 

But would this change be reflected without the change in the utils.js file?  
I am asking this because utils.js is the file from where we lookup whether the entered number is valid or invalid and I checked the file(https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/metadata.js) from where the data for utils.js is taken and found that the corresponding change has not been made in that file yet.

Would I need to do something else for this?

**Comment by jackocnr** [comment]
@abhishekbagria you could check the issues on the libphonenumber Github project and open a new one if there isn't already one.
