### ISSUE TITLE
Content Security Policy: Unsafe Inline

### ISSUE THREAD

**Issue by wschmrdrNS** [jackocnr/intl-tel-input#735]
With Content Security Policy being set to "self" for script-src within my nginx.conf file, and downloading/using the utils.js locally, when I go to display the telephone input box for the first time, the following is received:

Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (function(){var aa=this;function k(a){re....

intl-tel-input has the only utils.js file I have in my project that has this source string. It only happens once per refresh; I have a "single page app" where if I navigate somewhere else and then come back, it doesn't come up a second time. When Content Security Policy is disabled, I don't see any issues. Also, when I set script-src to "'self' 'unsafe-inline'", I don't see any issues. I am mandated to have Content Security Policy enabled, and would prefer not to have to add unsafe-inline since that defeats the purpose of the policy.

I am presently on intl-tel-input 12.1.13 .

**Comment by jackocnr** [comment]
I'm afraid I'm not familiar with nginx. Anyway your issue is not specific to this plugin - you can see that we just use jQuery's `$.ajax()` to load the utils.js script ([source code here](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L1349)), so I would recommend searching/asking about that specifically on stackoverflow. Good luck!
