### ISSUE TITLE
hiddenInput with Extensions

### ISSUE THREAD

**Issue by dotnetron** [jackocnr/intl-tel-input#737]
It appears that if the user enters any extension using an "x" or "ext" prefix etc. that value/string is not returned in the field used by the hiddenInput feature. Ideally I would like to store the number string in my back-end database with the extension e.g. "+12258190000 x211"

**Comment by jackocnr** [comment]
The problem is that the standard phone number format we use (E164) doesn't consider the extension to be part of the "true" phone number, so it gets stripped out. You need to use `getExtension` to extract the extension part and submit that separately. This is currently not supported by the `hiddenInput` option. An alternative would be to just have an additional small input to the right of the phone number input, and just handle the extension completely separately.
