### ISSUE TITLE
styling flags and arrow

### ISSUE THREAD

**Issue by TomasHurtz** [jackocnr/intl-tel-input#759]
best way to increase size of flag ?

best way to align arrow to rhs of input and add a background color?

I am using select2 for other inputs - so would like to match that style

![how to style better](https://user-images.githubusercontent.com/17046561/42223684-747cd2ba-7f2c-11e8-8e57-7d2c99137ae2.png)

**Comment by jackocnr** [comment]
Increasing the flag size is not trivial since the flag sprite is a PNG. But it can be done - on the demo site you'll find a link to a "Large flags" example, and there are some brief instructions listed there for achieving the same result yourself (or just grab the PNG/CSS I'm using in that example).

As for moving the country select from the left to the right - that's just some simple CSS tweaks - if you need help with that I'd recommend asking on StackOverflow.

**Comment by jackocnr** [comment]
> Thank you for the response :-)

You're welcome!

> but I don't understand what it means "Just tweak the numbers in the "retina" task in grunt/responsive_images.js"

You'll need to clone the project with git (or just download the whole project), and then you'll see there's a folder called grunt. See the Contributing section of the readme for instructions on how to setup the project yourself.

> As for moving the arrow, I did attempt this, but again, had no luck as it is inside the flag container which is positioned absolutely. It could be done using jquery, to shift the div out and then float right

You don't need to change the markup. To get you started, you would do something like this:

```css
.intl-tel-input .flag-container { right: 0; left: auto; }
.intl-tel-input .country-list { right: 0; width: 250px; }
```

No there's no plans to add an option for this in the plugin as it is easily done with a few lines of CSS. If you have further questions about this, please ask on StackOverflow.

**Comment by Gabsys** [comment]
> Increasing the flag size is not trivial since the flag sprite is a PNG. But it can be done - on the demo site you'll find a link to a "Large flags" example, and there are some brief instructions listed there for achieving the same result yourself (or just grab the PNG/CSS I'm using in that example).
> 
> As for moving the country select from the left to the right - that's just some simple CSS tweaks - if you need help with that I'd recommend asking on StackOverflow.

I followed the instruction on the "Large flags" example site but nothing changed. Am I missing something? I modified the **width and height in retina -> sizes of responsive_images.js** , modified **flagHeight and flagWidth of src -> css -> intlTelInput.scss** and ran "grunt build" (to be safe, I also ran "npm run build"). But turns out my flag size didn't change
