### ISSUE TITLE
It doesn't include the code of a country in a phone number

### ISSUE THREAD

**Issue by GildedHonour** [jackocnr/intl-tel-input#779]
```
    $("#person_phone_number").intlTelInput({
      initialCountry: "au",
      hiddenInput: "full_phone_number",
      utilsScript: "/assets/intlTelInput_utils.js"});

```

**Comment by jackocnr** [comment]
> It doesn't include the code of a country in a phone number

In what phone number? You mean the number displayed in the input? Or how are you getting the number? Using `getNumber` method?

**Comment by GildedHonour** [comment]
in POST data the code of a country isn't getting included. Only a number itself.

**Comment by GildedHonour** [comment]
I'm not using getNumber

**Comment by jackocnr** [comment]
Please make sure you're using the latest version of the plugin.

Please give a full example: say what the input value and selected country are when you submit, and then what values are being posted - there should be 2 - one with the name of the input and one with the name of your hidden input `full_phone_number`.

**Comment by GildedHonour** [comment]
When I specify a short phone number such as 2 characters, the code isn't getting included. Why?

whereas if I enter say 5 or more characters, the code is getting included.

**Comment by GildedHonour** [comment]
it's even stanger. I don't understand why sometimes it's included and why sometimes it's not.

does it depend whether or not I change a country?

**Comment by GildedHonour** [comment]
does it validate a number to decide whether or not include the code to it? 

if a number is too short or   long, the code isn't included?

**Comment by jackocnr** [comment]
The `hiddenInput` option uses `getNumber` internally, which expects a valid number. You should be doing your validation (see `isValidNumber`) before POSTing to your backend.

**Comment by jackocnr** [comment]
It's really complicated to add the country code to the number - it's not just a case of prefixing it, you have to know country specific rules e.g. in the UK we drop the leading zero. So we use libphonenumber's methods, which require a valid number.

Your options are to either (A) perform client side validation using the methods provided by this plugin, before submitting the number to your backend, or (B) disable nationalMode, which encourages the user to enter their full international number including country code, and then you dont need the `hiddenInput` option, you can just use the value from the input directly.

**Comment by GildedHonour** [comment]
how should I be able to validate a number on a server without a code then? what if validation rules of my system are different from the ones of libphonenumber? validation must be performed on a server anyway.

if I disable nationalMode, what'll be the point of using this library in the first place and not html textbox?

**Comment by GildedHonour** [comment]
also, how long is too long and too short?

**Comment by jackocnr** [comment]
> how should I be able to validate a number on a server without a code then?

If there is no code, I suppose you can assume it's invalid, since the frontend has already decided that.

> what if validation rules of my system are different from the ones of libphonenumber? validation must be performed on a server anyway.

Yes I agree you should always do server side validation as well. FYI I believe libphonenumber is the best solution out there for validating international phone numbers (it's maintained by Google, and is constantly updated with new validation rules as they change in the real world), and there are ports of libphonenumber available in PHP, Ruby etc if you're interested, but if you're not using that, then I guess there's a chance that the frontend will think a number is valid and allow posting to the backend, and then the backend will decide it's invalid and return an error. I don't see any issue with that - it just means the user will have to enter a number that is deemed valid by both the frontend and the backend.

> if I disable nationalMode, what'll be the point of using this library in the first place and not html textbox?

Most notably: the country dropdown, country-specific placeholders, formatting and validation. Take a look through the readme to get an idea of all the features you can still use e.g. `autoHideDialCode`, `autoPlaceholder`, `formatOnDisplay`, `geoIpLookup`, `separateDialCode`, `isValidNumber`, `getValidationError`, as well as features to customise the country dropdown e.g. `dropdownContainer`, `onlyCountries`, `localizedCountries`.

> also, how long is too long and too short?

Please see libphonenumber docs for more info on validation.

**Comment by GildedHonour** [comment]
Okay

When I do validation, I'm getting this



![captura de pantalla_2018-08-30_13-14-45](https://user-images.githubusercontent.com/2032888/44832991-ceb60380-ac56-11e8-9927-45ca7364089d.png)


Any idea why? What makes the flag move down?

That's validation styles used in a project and I want to stick with it so it's consistent

**Comment by jackocnr** [comment]
It looks like your custom CSS is clashing with the plugin's CSS - I'd recommend posting on Stackoverflow about this if you need help.

I'm going to close this issue for now, but feel free to open a new one if you experience another issue where you think there's something wrong with the plugin.
