### ISSUE TITLE
Some numbers are showing Invalid number

### ISSUE THREAD

**Issue by dotskapil** [jackocnr/intl-tel-input#793]
Hi,
I am using v9.0.6 version but I am facing a problem that **"63"** series phone numbers are not working when we select India country code. These series numbers are valid in India. Please help me to solve it.

**Comment by jackocnr** [comment]
Hi there, please update to the latest version and see if that fixes the problem. (Note that the main plugin is now pure JavaScript, but there is a separate jQuery version provided as well).

**Comment by jackocnr** [comment]
Also you can test the latest version on the demo site - see the validation example.

**Comment by dotskapil** [comment]
Hi, I have downloaded the latest version file utils.js and it's working fine now. But I want to ask you that should I update all the jquery files?

**Comment by jackocnr** [comment]
Oh great! Well v9.0.6 was released over 2 years ago - there have been many many bug fixes and improvements since then so I would highly recommend upgrading.

Also the updated utils.js may have fixed your validation issue, but I cannot guarantee that other aspects of utils haven't changed in the last 2 years so you may come across some other incompatibilities.
