### ISSUE TITLE
Does not get along with Bootstrap 4 validation tooltips

### ISSUE THREAD

**Issue by bbbenji** [jackocnr/intl-tel-input#807]
Because this script wraps the `input` in `div.flag-container`, the Bootstrap validation tooltip no longer works. Bootstrap expects the tooltip to be a direct sibling of a given `input`.

I am now contemplating a solution to this, but figure it was worth posting here.

You can see a quick demo of the issue in action: https://codepen.io/bbbenji/pen/VEEKZP

**Comment by jackocnr** [comment]
Hmm yeah that's tricky because the Bootstrap CSS selector relies on the `.invalid-tooltip` element to be a sibling to the input element. Only thing I can think off the top of my head is to dynamically insert the element next to the input after initialising the plugin e.g. something like this: https://codepen.io/jackocnr/pen/jeemNE

**Comment by bbbenji** [comment]
Can't argue with that workaround.

Here's a way to hit all tel inputs on a page instead of just the first one:

```
  let pnumbers =  document.querySelectorAll('.intl-tel-input')
  for (let item of pnumbers) {
    item.insertAdjacentHTML('beforeend', '<div class="invalid-tooltip">Please provide a valid phone number.</div>');
  }
```
However it doesn't depreciate if JS is disabled.

Feel free to close this.
