### ISSUE TITLE
0 added to the phone number when displaying it in the UI.

### ISSUE THREAD

**Issue by narasimhakamath** [jackocnr/intl-tel-input#824]
When I display the phone number in the UI, directly fetching it from the database, (918848519709 as stored in the DB, where 91 is the country code), the number will be in the input box as 08848519709, with the necessary flag and country code appearing, which isn't technically wrong, but not the phone number format I intend to show.

I did change the separateDialCode to 1, which helped me fix the issue, also by changing the necessary CSS in the library. But I wanted to know if doing so will break elsewhere.

Thanks!

**Comment by jackocnr** [comment]
> I did change the separateDialCode to 1, which helped me fix the issue

What was the issue? Isn't 08848519709 the standard way to display a phone number?

**Comment by narasimhakamath** [comment]
Without any changes in the jQuery file, the number is displayed with a 0 added at the front.
I want to display the number as 918848519709 OR as 8848519709, which was possible with the help of separateDialCode, where the +91 will appear with the flag for the selected code.

I want to know if changing the value of separateDialCode will affect somewhere else or break some other feature that depends on this value.

What other purpose does the variable separateDialCode serve in the file?

This isn't exactly as issue with the library, but what I want to know is if I modify the library, will it break? (separateDialCode variable)

**Comment by narasimhakamath** [comment]
The 0 at the front did have a significant part when interstate calls were made. But things have changed now (India) and we don't really need to dial with the 0 at the front to make the calls anymore. So is there any possible way to modify the jQuery file in my project or can that part be done from your side?

**Comment by jackocnr** [comment]
> Without any changes in the jQuery file, the number is displayed with a 0 added at the front.

This is because `nationalMode` is enabled by default, which formats numbers to the standard national format, using [libphonenumber](https://github.com/googlei18n/libphonenumber/) - if you think this is incorrect, you should file an issue with them. Note that in many countries, the national format of the number has an added digit (e.g. in the UK it's the same with the added 0 at the front), and without that the number is invalid, and just looks wrong.

Enabling the `separateDialCode` option changes this so you're now dealing with numbers in the international format, and then it literally just extracts the international dial code (+91 for India) from the number and displays it next to the flag instead. You just have to be careful now because the number in the input on it's own is not a valid number - it is just part of the full international number. But as long as you use the plugin methods to read the number you'll be fine e.g. `isValidNumber` or `getNumber` - these methods will first prefix the number with the international dial code to get the full number.

Does that make sense?
