### ISSUE TITLE
Export allCountries from data.js ?

### ISSUE THREAD

**Issue by jscti** [jackocnr/intl-tel-input#838]
Hi there

Would it be possible to export `allCountries` somehow in the data.js file ?
I'm trying to use it in an angular project (without loading all your lib) but cannot import/require it.

Thanks

**Comment by sunsande** [comment]
As addition to it - what is the source of this list/how was it build?

Thanks!

**Comment by jscti** [comment]
> As addition to it - what is the source of this list/how was it build?
> 
> Thanks!

The comment on this file is : 

> // Here is the criteria for the plugin to support a given country/territory
> // - It has an iso2 code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
> // - It has it's own country calling code (it is not a sub-region of another country): https://en.wikipedia.org/wiki/List_of_country_calling_codes
> // - It has a flag in the region-flags project: https://github.com/behdad/region-flags/tree/gh-pages/png
> // - It is supported by libphonenumber (it must be listed on this page): https://github.com/googlei18n/libphonenumber/blob/master/resources/ShortNumberMetadata.xml
>

**Comment by jackocnr** [comment]
@jscti src/js/data.js defines a `allCountries` variable, so if you load that script on your page, it should define that variable globally. If you're using some sort of bundling tool like Webpack and you want to import that variable as a local variable, you'll need to look into shimming e.g. https://webpack.js.org/guides/shimming/#global-exports

@sunsande see the [Attributions](https://github.com/jackocnr/intl-tel-input#attributions) section of the readme for the original source of the data. It has since been modified a lot by hand - feel free to browse the git history!

**Comment by jscti** [comment]
Well yeah it was to import it as a local variable without webpack .. so I guess I'll abandon the idea.
