### ISSUE TITLE
Country delect arrow position wrong if three digit country code as +358 (fi)

### ISSUE THREAD

**Issue by mwenell** [jackocnr/intl-tel-input#859]
IMPORTANT: please read the New Issue Checklist before creating a new issue: https://github.com/jackocnr/intl-tel-input/wiki/New-Issue-Checklist

### Steps to reproduce
1.  Set separateDialCode: true
2.  Select fi +358 (Finland)
3.  See that dropdown selector arrow is on top of last digit 8

### Expected behaviour
Arrow should be after the country dialcode, not over it.

### Actual behaviour
Arrow is partly over the last digit 8.

### Initialisation options
var input = document.querySelector("#phone");window.intlTelInput(input, {autoPlaceholder: "polite", preferredCountries: ["fi"], separateDialCode: true, initialCountry: "fi",
  utilsScript: "http://test.multisite.com/wp-content/plugins/Sample-Valley-2/lib/intlTelInput/js/utils.js"});

### How to Fix
Javascript does not use the length (?) of dial code element (selected-dial-code) to set the width of the parent (selected-flag) correctly. My quick fix is to use smaller font as follows:
<style>.selected-dial-code {font-size: 14px;}</style>

**Comment by jackocnr** [comment]
Yeah unfortunately there is no easy workaround for this at the moment, because the implementation hardcodes a bunch of widths [in the CSS](https://github.com/jackocnr/intl-tel-input/blob/master/src/css/intlTelInput.scss#L258) depending on how many characters are in the displayed dial code.

Technically you could override [the generated CSS](https://github.com/jackocnr/intl-tel-input/blob/master/build/css/intlTelInput.css#L109-L140) to tweak those widths to match your font size, but honestly that would be a lot of work.

So yeah currently the only reasonable workaround is to tweak the font-size as you have found. But I would welcome a PR to update the `separateDialCode` implementation so that it can be more flexible, so there are no hardcoded widths and instead it reacts to the text, no matter what the font size is.

**Comment by mwenell** [comment]
I think you are right. I'm going to use smaller font now.

As you wrote the best way is to get the width of the text from the dialcode's element's width and use it in your Javascript.

Thanks.

**Comment by mwenell** [comment]
Could you do it without position: absolut?

I would do it something like below (untested example). Without positioning and just using block-inline and let the width of things happen automatically. This may not work for some reason, but maybe it is worth of testing.

<style>
.inputFrame {
  border: 1px solid gray;
}
.inputFrame > div,.inputFrame > input {
  display: inline-block;
}
.inputFrame > input {
  border: 0px;
}
</style>
<div class="inputFrame">
  <div>FLAG STUFF HERE WITH display:none show</div>
  <div>Country code here</div>
  <div>Arrow here</div>
  <input>
</div>

**Comment by jackocnr** [comment]
Fixed in v14.0.10.
