### ISSUE TITLE
Does not display default flag

### ISSUE THREAD

**Issue by Malolan-Balaji-T18128** [jackocnr/intl-tel-input#888]
### Steps to reproduce
During execution of `_setInitialState()` method, all properties are set to default except the input value (`val`) which gets the value  `"8623731932"` (for example).

### Expected behaviour
Should display US flag by default

### Actual behaviour
No flag is being displayed

### Initialisation options
all the properties are default.

**Comment by jackocnr** [comment]
I assume you're initialising the plugin on an input with the value "8623731932"? There's no way for the plugin to know which country that number belongs to because you haven't included the international dial code. In the [Recommended Usage](https://github.com/jackocnr/intl-tel-input#recommended-usage) section we recommend you only ever deal with numbers in the full international format. Alternatively you can call setCountry.
