### ISSUE TITLE
IE11 - hiddenInput value is not sent when form is submitted via jQuery

### ISSUE THREAD

**Issue by xkovacikm** [jackocnr/intl-tel-input#945]
Hi,

I've got a problem.  Front-end validation of phone number works perfectly, but after sending a POST request to server, input is empty.

I use hiddenInput option.

Sorry for humble description. If you need more info, just tell me. 

Thanks

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by xkovacikm** [comment]
Sorry, codepen not working properly with internet explorer ( Edge only ) so there is impossible for me to make some code. But i created my own page with example.

http://intl.mockup.sk/
This example sends data on modern browsers but IE 11 & below don't.
Please open developer console to check the code.

Problem is when you submit form with button which is **outside** form.
HTML5 attribute "form" is not working for older browsers so i used workaround.
`<button type="submit" form="form" tabindex="0" onclick="!this.form&&$('#' + $(this).attr('form')).submit()">Submit</button>`

So i assume submitting form by Jquery .submit() function does not work

Thank you and sorry for late response :)

**Comment by xkovacikm** [comment]
Maybe this is a problem? **The JavaScript submit event does not bubble in Internet Explorer.**

**Comment by jackocnr** [comment]
Thank you for creating that demo page. I can confirm the issue in IE11.

As an aside, I think the button type should be 'button' since it is not in inside a `<form>`.

I'm not sure of the solution to this. All the submit listener does is populate the hidden input value with the result of `getNumber` (see [this single line of code](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L472)) - perhaps you could just do this yourself before submitting the form? e.g.

`document.querySelector('[name=hiddenTel]').value = window.iti.getNumber()`

**Comment by xkovacikm** [comment]
yeah i did similar hotfix already.
