### ISSUE TITLE
ID Attribute value generated by plugin are not unique.

### ISSUE THREAD

**Issue by melwinantony** [jackocnr/intl-tel-input#960]
### Steps to reproduce
Initiate the plugin with preferredCountries set ( e.g. us,gb ) , the code generated by the plugin would have duplicated ID Attribute value. The value "iti-item-us" and "iti-item-gb" will appear twice in the generated code.

### Expected behaviour
ID Attribute value generated by the plugin should be Unique even with preferred countries set.

### Actual behaviour
When the preferedCountries are set, The countries which are included in preferred Countries appear once in the top of the List and again it appears based on the regular order and both the times it holds the same ID Attribute value causing an duplicated ID values.

**Comment by jackocnr** [comment]
Hmm that's a good point. Maybe we should just remove the ID for those preferred country list items. Needs a bit of thought.

**Comment by scottadamsmith** [comment]
Chiming in here since I mentioned this in my other issue in addition to the ID on the container element for the country list. Definitely feels like there are multiple ways to address this:

* Only render preferred countries at the top and not additionally in the list below. 
* Replace the ID attribute with something else that can be used as a selector, a data attribute or class perhaps. Something that doesn't have a unique requirement. That still leads to the question, what should be selected when you open it again after picking a preferred country? The preferred country or it's regular listing below?

Those are just a couple of ideas I had to get a discussion going.

**Comment by jackocnr** [comment]
Thanks for your thoughts @scottadamsmith. To respond to those points:

> Only render preferred countries at the top and not additionally in the list below.

I don't want to do this - I think it would be confusing if you were scrolling through the list and a country was missing.

> what should be selected when you open it again after picking a preferred country? The preferred country or it's regular listing below?

I would say the regular listing.

Which makes me think @RomanBaiocco's solution was the best option, but he closed the PR - can I ask why? Did you find any issues with that approach? Thanks.

**Comment by jackocnr** [comment]
After trying it out, I decided it felt more intuitive to scroll to the preferred item if available.

Fix released in v17.
