### ISSUE TITLE
Flags not showing

### ISSUE THREAD

**Issue by Jessicasciani** [jackocnr/intl-tel-input#985]
Hello

I would like to know where the images of the flags are coming from ?

1.  I am using webpacker with Rails and had to make a few changes to make it work. I've imported the sprite and intl-tel-input stylesheets manually and everything works properly. I see all countries + country codes and my input looks good

2.  The only stuff not working is that the flags are not showing at all. I've tried to change the css to the one provided in the doc, but still not working.

Where can I find the flag images so I can import them manually too ? Where are those images coming from?

Thanks a lot

**Comment by jackocnr** [comment]
Hi Jessica, the images can be found in the build/img/ directory. You will need to host these somewhere and override the relevant CSS rules with the new paths (see Getting Started section of readme). Does that answer your question?

**Comment by Jessicasciani** [comment]
It does and that works

Thanks a lot!!

**Comment by KevinBongart** [comment]
In case that's useful to anyone else, here's how I made it work with Ruby on Rails 6.1 and Webpacker:

```sh
yarn add intl-tel-input
cp node_modules/intl-tel-input/build/css/intlTelInput.css app/javascript/stylesheets/vendor/intl_tel_input.scss
cp node_modules/intl-tel-input/build/img/flags.png node_modules/intl-tel-input/build/img/flags@2x.png app/javascript/images/vendor/intl_tel_input
```

The above adds `intl-tel-input` to the yarn bundle, then copies the library's stylesheet to the application's stylesheets and the library's flag images to the application's images.

Then, at the bottom of the `app/javascript/stylesheets/vendor/intl_tel_input.scss` file, replace the paths to the flag images so that it finds them in the application asset pack:

```diff
 .iti__flag {
   height: 15px;
   box-shadow: 0px 0px 1px 0px #888;
-  background-image: url("../img/flags.png");
+  background-image: url("~images/vendor/intl_tel_input/flags.png");
   background-repeat: no-repeat;
   background-color: #DBDBDB;
   background-position: 20px 0; }
   @media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
     .iti__flag {
-      background-image: url("../img/flags@2x.png"); } }
+      background-image: url("~images/vendor/intl_tel_input/flags@2x.png"); } }
```

On the Javascript side, proceed as described in the README or, if you're using Stimulus.js:

```erb
<div data-controller="phone-input">
  <%= f.input_field :phone_number, data: { "phone-input-target": "input" } %>
</div>
```

and in the Stimulus.js controller `app/javascript/controllers/phone_input_controller.js`:

```js
import { Controller } from "stimulus"
import intlTelInput from "intl-tel-input";

export default class extends Controller {
  static targets = ["input"]

  connect() {
    intlTelInput(this.inputTarget, {
      // any initialisation options go here
    });
  }
}
```
